// prologue.js — 4 сцены пролога Python-режима.
// (см. LDB §4)

export const PROLOGUE_SCENES = [
  {
    id: 'p1',
    title: 'Первое слово',
    goal: 'Тапни ▶ показать',
    presetCode: 'print("Привет")',
    editable: false,
    scene: 'stage',
    successOn: 'ProgramEnd',
    profikIntro: null,
    profikOutro: 'Ты пришёл. Я знал.',
    targetTimeMs: 15_000,
    xpReward: 5,
  },
  {
    id: 'p2',
    title: 'Коробка',
    goal: 'Положи в коробку имя',
    presetCode: 'name = "Друг"\nprint("Привет, " + name)',
    editable: false,
    scene: 'stage',
    successOn: 'ProgramEnd',
    profikOutro: 'Приятно познакомиться.',
    targetTimeMs: 10_000,
    xpReward: 5,
  },
  {
    id: 'p3',
    title: 'Две команды',
    goal: 'Профик скажет раз, потом два',
    presetCode: 'print("раз")\nprint("два")',
    editable: false,
    scene: 'stage',
    successOn: 'ProgramEnd',
    profikOutro: 'Считалка.',
    targetTimeMs: 8_000,
    xpReward: 5,
  },
  {
    id: 'p4',
    title: 'Пять раз',
    goal: 'Пусть скажет ура пять раз',
    presetCode: 'for i in range(5):\n    print("ура")',
    editable: false,
    scene: 'stage',
    successOn: 'ProgramEnd',
    profikOutro: 'Это уже интереснее. Пошли в Дюны.',
    targetTimeMs: 15_000,
    xpReward: 10,
  },
];
