// ege.js — программа уровня ЕГЭ: функции, списки, словари, библиотеки, алгоритмы.

export const EGE_UNITS = [
  // ── Юнит 9 ────────────────────────────────
  {
    id: 'ege_lists',
    level: 'Продвинутый',
    icon: '📚',
    color: '#f59e0b',
    title: 'Списки',
    desc: 'Массивы, индексы, методы',
    lessons: [
      {
        id: 'ege_lists_1',
        title: 'Основы списков',
        xp: 15,
        questions: [
          { type: 'output', q: 'Что выведет программа?',
            code: 'a = [10, 20, 30]\nprint(a[1])',
            answer: '20',
            explain: 'Индексация с нуля: a[1] — второй элемент, 20.' },
          { type: 'output', q: 'Что выведет программа?',
            code: 'a = [5, 8, 3]\nprint(len(a))',
            answer: '3',
            explain: 'len() — количество элементов в списке.' },
          { type: 'output', q: 'Что выведет программа?',
            code: 'a = [1, 2, 3]\na.append(4)\nprint(a)',
            answer: '[1, 2, 3, 4]',
            explain: 'append(4) добавляет 4 в конец списка.' },
          { type: 'output', q: 'Что выведет программа?',
            code: 'a = [3, 1, 2]\na.sort()\nprint(a)',
            answer: '[1, 2, 3]',
            explain: 'sort() сортирует список по возрастанию.' },
          { type: 'output', q: 'Что выведет программа?',
            code: 'a = [10, 20, 30]\ns = 0\nfor x in a:\n    s = s + x\nprint(s)',
            answer: '60',
            explain: 'Сумма элементов: 10+20+30 = 60.' },
          { type: 'assemble', q: 'Собери: создай список [1,2,3] и выведи сумму',
            lines: ['a = [1, 2, 3]', 'print(sum(a))'],
            explain: 'sum() сразу считает сумму всех элементов.' },
        ],
      },
      {
        id: 'ege_lists_2',
        title: 'Срезы и методы',
        xp: 15,
        questions: [
          { type: 'output', q: 'Что выведет программа?',
            code: 'a = [0, 1, 2, 3, 4]\nprint(a[1:3])',
            answer: '[1, 2]',
            explain: 'Срез a[1:3] — элементы с 1 по 2 (правая граница 3 не входит).' },
          { type: 'output', q: 'Что выведет программа?',
            code: 'a = [5, 2, 8, 1]\nprint(max(a))',
            answer: '8',
            explain: 'max() возвращает наибольший элемент.' },
          { type: 'output', q: 'Что выведет программа?',
            code: 'a = [5, 2, 8, 1]\nprint(min(a))',
            answer: '1',
            explain: 'min() возвращает наименьший элемент.' },
          { type: 'mcq', q: 'Как получить список из 5 нулей?',
            options: ['[0]*5', '[0,5]', 'list(5)', '[5*0]'], answer: 0,
            explain: '[0]*5 повторяет элемент: [0, 0, 0, 0, 0].' },
        ],
      },
    ],
  },

  // ── Юнит 10 ───────────────────────────────
  {
    id: 'ege_nested',
    level: 'Продвинутый',
    icon: '🔳',
    color: '#f59e0b',
    title: 'Вложенные циклы',
    desc: 'Циклы внутри циклов',
    lessons: [
      {
        id: 'ege_nested_1',
        title: 'Цикл в цикле',
        xp: 15,
        questions: [
          { type: 'output', q: 'Сколько раз выполнится print?',
            code: 'k = 0\nfor i in range(3):\n    for j in range(2):\n        k = k + 1\nprint(k)',
            answer: '6',
            explain: 'Внешний 3 раза × внутренний 2 раза = 6.' },
          { type: 'output', q: 'Что выведет программа?',
            code: 'for i in range(1, 3):\n    for j in range(1, 3):\n        print(i, j)',
            answer: '1 1\n1 2\n2 1\n2 2',
            explain: 'Для каждого i перебираются все j.' },
          { type: 'output', q: 'Что выведет программа?',
            code: 's = 0\nfor i in range(1, 4):\n    for j in range(1, 4):\n        s = s + 1\nprint(s)',
            answer: '9',
            explain: '3 × 3 = 9 итераций.' },
        ],
      },
    ],
  },

  // ── Юнит 11 ───────────────────────────────
  {
    id: 'ege_func',
    level: 'Продвинутый',
    icon: '⚙️',
    color: '#f59e0b',
    title: 'Функции',
    desc: 'def, параметры, return',
    lessons: [
      {
        id: 'ege_func_1',
        title: 'Свои функции',
        xp: 15,
        questions: [
          { type: 'output', q: 'Что выведет программа?',
            code: 'def kvadrat(x):\n    return x * x\nprint(kvadrat(5))',
            answer: '25',
            explain: 'Функция возвращает x*x. Для 5 это 25.' },
          { type: 'mcq', q: 'Что делает return в функции?',
            options: ['Печатает значение', 'Возвращает результат', 'Создаёт цикл', 'Завершает программу'],
            answer: 1,
            explain: 'return передаёт результат туда, откуда функцию вызвали.' },
          { type: 'output', q: 'Что выведет программа?',
            code: 'def summa(a, b):\n    return a + b\nprint(summa(3, 4))',
            answer: '7',
            explain: 'summa(3, 4) возвращает 3 + 4 = 7.' },
          { type: 'output', q: 'Что выведет программа?',
            code: 'def f(n):\n    return n % 2 == 0\nprint(f(10))',
            answer: 'True',
            explain: '10 чётное, поэтому 10 % 2 == 0 истинно — True.' },
          { type: 'assemble', q: 'Собери функцию, возвращающую куб числа',
            lines: ['def cube(x):', '    return x ** 3', 'print(cube(2))'],
            explain: 'Определение функции, тело с return, затем вызов.' },
        ],
      },
    ],
  },

  // ── Юнит 12 ───────────────────────────────
  {
    id: 'ege_str2',
    level: 'Продвинутый',
    icon: '✂️',
    color: '#ec4899',
    title: 'Строки продвинуто',
    desc: 'Срезы, методы строк',
    lessons: [
      {
        id: 'ege_str2_1',
        title: 'Срезы строк',
        xp: 15,
        questions: [
          { type: 'output', q: 'Что выведет программа?',
            code: 's = "информатика"\nprint(s[0:4])',
            answer: 'инфо',
            explain: 'Срез s[0:4] — символы с 0 по 3.' },
          { type: 'output', q: 'Что выведет программа?',
            code: 's = "Python"\nprint(s[::-1])',
            answer: 'nohtyP',
            explain: 'Срез [::-1] переворачивает строку.' },
          { type: 'output', q: 'Что выведет программа?',
            code: 's = "abc"\nprint(s.upper())',
            answer: 'ABC',
            explain: 'upper() делает все буквы заглавными.' },
          { type: 'output', q: 'Что выведет программа?',
            code: 's = "hello world"\nprint(s.count("o"))',
            answer: '2',
            explain: 'count("o") считает вхождения "o": их 2.' },
          { type: 'output', q: 'Что выведет программа?',
            code: 's = "1,2,3"\nprint(s.split(","))',
            answer: "['1', '2', '3']",
            explain: 'split(",") разбивает строку по запятой в список.' },
        ],
      },
    ],
  },

  // ── Юнит 13 ───────────────────────────────
  {
    id: 'ege_dict',
    level: 'Продвинутый',
    icon: '🗂️',
    color: '#ec4899',
    title: 'Словари и множества',
    desc: 'dict, set — ключ и значение',
    lessons: [
      {
        id: 'ege_dict_1',
        title: 'Словари',
        xp: 15,
        questions: [
          { type: 'output', q: 'Что выведет программа?',
            code: 'd = {"a": 1, "b": 2}\nprint(d["b"])',
            answer: '2',
            explain: 'd["b"] — значение по ключу "b", равно 2.' },
          { type: 'mcq', q: 'Для чего удобен словарь?',
            options: ['Хранить пары ключ-значение', 'Только числа', 'Сортировать', 'Циклы'],
            answer: 0,
            explain: 'Словарь хранит соответствие: ключ → значение.' },
          { type: 'output', q: 'Что выведет программа? (подсчёт букв)',
            code: 'd = {}\nfor c in "aab":\n    d[c] = d.get(c, 0) + 1\nprint(d["a"])',
            answer: '2',
            explain: 'get(c, 0) возвращает текущее число или 0. "a" встретилось 2 раза.' },
          { type: 'output', q: 'Что выведет программа?',
            code: 's = {1, 2, 2, 3, 3, 3}\nprint(len(s))',
            answer: '3',
            explain: 'Множество хранит только уникальные: {1, 2, 3} — 3 элемента.' },
        ],
      },
    ],
  },

  // ── Юнит 14 ───────────────────────────────
  {
    id: 'ege_lib',
    level: 'Продвинутый',
    icon: '📦',
    color: '#8b5cf6',
    title: 'Библиотеки',
    desc: 'math, random и другие',
    lessons: [
      {
        id: 'ege_lib_1',
        title: 'Модуль math',
        xp: 15,
        questions: [
          { type: 'mcq', q: 'Как подключить модуль math?',
            options: ['import math', 'include math', 'use math', 'load math'], answer: 0,
            explain: 'import math подключает библиотеку математики.' },
          { type: 'output', q: 'Что выведет программа?',
            code: 'import math\nprint(math.sqrt(16))',
            answer: '4.0',
            explain: 'sqrt(16) — квадратный корень, 4.0 (дробный).' },
          { type: 'output', q: 'Что выведет программа?',
            code: 'import math\nprint(math.factorial(4))',
            answer: '24',
            explain: 'factorial(4) = 1·2·3·4 = 24.' },
          { type: 'mcq', q: 'Что делает random.randint(1, 6)?',
            options: ['Всегда 6', 'Случайное число от 1 до 6', 'Число 1.6', 'Список 1..6'],
            answer: 1,
            explain: 'randint(1, 6) — случайное целое от 1 до 6 включительно.' },
          { type: 'output', q: 'Что выведет программа?',
            code: 'import math\nprint(math.pi > 3)',
            answer: 'True',
            explain: 'math.pi ≈ 3.1415, что больше 3 — True.' },
        ],
      },
    ],
  },

  // ── Юнит 15 ───────────────────────────────
  {
    id: 'ege_algo',
    level: 'Продвинутый',
    icon: '🎯',
    color: '#8b5cf6',
    title: 'Задачи ЕГЭ',
    desc: 'Разбор типовых заданий',
    lessons: [
      {
        id: 'ege_algo_1',
        title: 'Обработка чисел',
        xp: 20,
        questions: [
          { type: 'output', q: 'Что выведет программа? (сумма цифр числа 253)',
            code: 'n = 253\ns = 0\nwhile n > 0:\n    s = s + n % 10\n    n = n // 10\nprint(s)',
            answer: '10',
            explain: 'Цифры 2+5+3 = 10. n%10 берёт последнюю цифру, n//10 убирает её.' },
          { type: 'output', q: 'Что выведет программа? (максимум из списка)',
            code: 'a = [3, 7, 2, 9, 4]\nm = a[0]\nfor x in a:\n    if x > m:\n        m = x\nprint(m)',
            answer: '9',
            explain: 'Классический поиск максимума перебором. Наибольшее — 9.' },
          { type: 'output', q: 'Что выведет программа? (сколько чисел > 5)',
            code: 'a = [3, 8, 5, 9, 2, 7]\nk = 0\nfor x in a:\n    if x > 5:\n        k = k + 1\nprint(k)',
            answer: '3',
            explain: 'Больше 5: это 8, 9, 7 — три числа.' },
          { type: 'output', q: 'Что выведет программа? (количество делителей 12)',
            code: 'n = 12\nk = 0\nfor d in range(1, n + 1):\n    if n % d == 0:\n        k = k + 1\nprint(k)',
            answer: '6',
            explain: 'Делители 12: 1,2,3,4,6,12 — шесть штук.' },
        ],
      },
    ],
  },
];
