// ege_libs.js — библиотеки для ЕГЭ (глава 15). Партия 1.
// Новые темы уровня ЕГЭ, привязанные к номерам задач.

export const EGE_LIB_UNITS = [
  // ── math расширенный (задачи 7, 11, 14, 16) ──
  {
    id: 'ege_math_full',
    level: 'Продвинутый',
    icon: '📐',
    color: '#8b5cf6',
    title: 'math для ЕГЭ',
    desc: 'ceil, floor, sqrt, gcd, log2, factorial',
    lessons: [
      {
        id: 'ege_math_full_1', title: 'Округление и корни', xp: 15,
        questions: [
          { type: 'output', q: 'Что выведет программа?', code: 'from math import ceil\nprint(ceil(3.2))', answer: '4',
            explain: 'ceil округляет ВВЕРХ: 3.2 → 4.' },
          { type: 'output', q: 'Что выведет программа?', code: 'from math import floor\nprint(floor(3.8))', answer: '3',
            explain: 'floor округляет ВНИЗ: 3.8 → 3.' },
          { type: 'output', q: 'Что выведет программа?', code: 'from math import sqrt\nprint(sqrt(16))', answer: '4.0',
            explain: 'sqrt — квадратный корень, результат дробный: 4.0.' },
          { type: 'output', q: 'Что выведет программа?', code: 'print(16 ** 0.5)', answer: '4.0',
            explain: 'Степень 0.5 — тоже квадратный корень: 4.0.' },
          { type: 'output', q: 'Что выведет программа?', code: 'print(pow(2, 10))', answer: '1024',
            explain: 'pow(2, 10) = 2 в степени 10 = 1024.' },
          { type: 'mcq', q: 'Какое округление даёт ceil(4.1)?',
            options: ['5', '4', '4.1', '3'], answer: 0,
            explain: 'ceil всегда вверх: 4.1 → 5.' },
          { type: 'bug', q: 'Почему ошибка «name ceil is not defined»?', code: 'print(ceil(3.2))',
            options: ['Забыли from math import ceil', 'ceil не существует', 'Нужны кавычки', 'Всё верно'], answer: 0,
            explain: 'Перед использованием ceil надо подключить: from math import ceil.' },
        ],
      },
      {
        id: 'ege_math_full_2', title: 'НОД, логарифмы, факториал', xp: 15,
        questions: [
          { type: 'output', q: 'Что выведет программа?', code: 'from math import gcd\nprint(gcd(12, 18))', answer: '6',
            explain: 'gcd — наибольший общий делитель. НОД(12,18)=6.' },
          { type: 'output', q: 'Что выведет программа?', code: 'from math import gcd\nprint(gcd(12, 18, 24))', answer: '6',
            explain: 'gcd может принимать несколько чисел (Python 3.9+). НОД=6.' },
          { type: 'output', q: 'Что выведет программа?', code: 'from math import log2\nprint(log2(8))', answer: '3.0',
            explain: 'log2(8) = 3.0, потому что 2 в степени 3 = 8.' },
          { type: 'output', q: 'Что выведет программа? (сколько бит на 1000 символов)', code: 'from math import ceil, log2\nprint(ceil(log2(1000)))', answer: '10',
            explain: 'log2(1000)≈9.97, ceil→10. Задача 11: столько бит нужно на код.' },
          { type: 'output', q: 'Что выведет программа?', code: 'from math import factorial\nprint(factorial(5))', answer: '120',
            explain: '5! = 1·2·3·4·5 = 120.' },
          { type: 'output', q: 'Что выведет программа?', code: 'from math import log\nprint(log(100, 10))', answer: '2.0',
            explain: 'log(100, 10) — логарифм 100 по основанию 10 = 2.0.' },
          { type: 'mcq', q: 'Какой инструмент нужен в задаче 11 для подсчёта бит на символ?',
            options: ['ceil(log2(N))', 'floor(N)', 'sqrt(N)', 'gcd(N)'], answer: 0,
            explain: 'Количество бит = ceil(log2(количество символов)).' },
          { type: 'mcq', q: 'Что вернёт gcd(15, 25)?', code: 'from math import gcd\nprint(gcd(15, 25))',
            options: ['5', '3', '75', '10'], answer: 0,
            explain: 'НОД(15, 25) = 5.' },
        ],
      },
    ],
  },

  // ── itertools (задачи 8, 15) ──
  {
    id: 'ege_itertools',
    level: 'Продвинутый',
    icon: '🔀',
    color: '#8b5cf6',
    title: 'itertools (задачи 8, 15)',
    desc: 'product, permutations, combinations',
    lessons: [
      {
        id: 'ege_itertools_1', title: 'Перебор комбинаций', xp: 15,
        questions: [
          { type: 'output', q: 'Что выведет программа?', code: "from itertools import product\nfor p in product('АБ', repeat=2):\n    print(''.join(p))", answer: 'АА\nАБ\nБА\nББ',
            explain: 'product с repeat=2 — все слова длины 2 с повторами.' },
          { type: 'output', q: 'Сколько всего слов?', code: "from itertools import product\na = list(product('АБВ', repeat=2))\nprint(len(a))", answer: '9',
            explain: '3 буквы, длина 2, с повторами: 3·3 = 9.' },
          { type: 'output', q: 'Сколько слов?', code: "from itertools import product\nprint(len(list(product('01', repeat=3))))", answer: '8',
            explain: '2 символа, длина 3: 2·2·2 = 8.' },
          { type: 'output', q: 'Что выведет программа?', code: "from itertools import permutations\nfor p in permutations('АБВ', 2):\n    print(''.join(p))", answer: 'АБ\nАВ\nБА\nБВ\nВА\nВБ',
            explain: 'permutations — перестановки БЕЗ повторов, порядок важен.' },
          { type: 'output', q: 'Сколько перестановок?', code: "from itertools import permutations\nprint(len(list(permutations('АБВГ', 2))))", answer: '12',
            explain: 'Из 4 по 2 без повторов: 4·3 = 12.' },
          { type: 'output', q: 'Что выведет программа?', code: 'from itertools import combinations\nfor c in combinations([1, 2, 3], 2):\n    print(c)', answer: '(1, 2)\n(1, 3)\n(2, 3)',
            explain: 'combinations — сочетания, порядок НЕважен, без повторов.' },
          { type: 'output', q: 'Сколько сочетаний?', code: 'from itertools import combinations\nprint(len(list(combinations([1, 2, 3, 4], 2))))', answer: '6',
            explain: 'Из 4 по 2: (1,2)(1,3)(1,4)(2,3)(2,4)(3,4) — 6 пар.' },
          { type: 'mcq', q: 'Какой инструмент нужен в задаче 8 (слова с повторами букв)?',
            options: ['product', 'combinations', 'gcd', 'sqrt'], answer: 0,
            explain: 'product(repeat=n) даёт все слова длины n с повторами — это задача 8.' },
          { type: 'bug', q: 'Почему print(p) даёт («А», «Б»), а не «АБ»?', code: "from itertools import product\nfor p in product('АБ', repeat=2):\n    print(p)",
            options: ['product даёт кортежи, нужен "".join(p)', 'Ошибка', 'Так и надо', 'repeat неверный'], answer: 0,
            explain: 'product возвращает кортежи. Чтобы склеить в строку — "".join(p).' },
        ],
      },
    ],
  },

  // ── functools / рекурсия (задача 16) ──
  {
    id: 'ege_recursion',
    level: 'Продвинутый',
    icon: '🔁',
    color: '#8b5cf6',
    title: 'Рекурсия и кэш (задача 16)',
    desc: 'lru_cache, безопасный массив',
    lessons: [
      {
        id: 'ege_recursion_1', title: 'Кэш и рекурсия', xp: 15,
        questions: [
          { type: 'output', q: 'Что выведет программа?', code: 'def F(n):\n    if n <= 2:\n        return n\n    return F(n - 1) + F(n - 2)\nprint(F(6))', answer: '13',
            explain: 'F1=1, F2=2, дальше сумма двух предыдущих: F3=3, F4=5, F5=8, F6=13.' },
          { type: 'mcq', q: 'Зачем нужен @lru_cache в задаче 16?',
            options: ['Запоминает уже посчитанное — рекурсия не тормозит', 'Ускоряет вывод', 'Меняет ответ', 'Для красоты'], answer: 0,
            explain: 'lru_cache кэширует результаты, поэтому глубокая рекурсия считается мгновенно.' },
          { type: 'bug', q: 'Как правильно поставить @lru_cache?',
            options: ['Прямо над def, без пустой строки', 'После функции', 'Внутри функции', 'В конце программы'], answer: 0,
            explain: '@lru_cache(10000) ставится строго над def, без пустой строки между ними.' },
          { type: 'output', q: 'Что выведет безопасный массив (без рекурсии)?', code: 'F = [0] * 10\nfor n in range(10):\n    if n < 3:\n        F[n] = n + 2\n    else:\n        F[n] = F[n - 1] + 1\nprint(F[9])', answer: '11',
            explain: 'F0=2,F1=3,F2=4, дальше +1: F3=5,F4=6,F5=7,F6=8,F7=9,F8=10,F9=11.' },
          { type: 'mcq', q: 'Что надёжнее рекурсии на ЕГЭ при больших n?',
            options: ['Заполнить массив F[n] циклом', 'Поднять лимит рекурсии', 'Ничего', 'Использовать while True'], answer: 0,
            explain: 'Массив F[n], заполненный циклом от начала — самый надёжный способ (задача 16).' },
          { type: 'mcq', q: 'Почему НЕ советуют setrecursionlimit на ЕГЭ?',
            options: ['Python может «упасть» на проверке — потеря баллов', 'Это запрещено', 'Слишком медленно', 'Не работает'], answer: 0,
            explain: 'Поднятие лимита нестабильно, программа может упасть. Лучше lru_cache или массив.' },
        ],
      },
    ],
  },

  // ── re регулярки (задача 24) ──
  {
    id: 'ege_re',
    level: 'Продвинутый',
    icon: '🔎',
    color: '#ec4899',
    title: 'Регулярки re (задача 24)',
    desc: 'findall, finditer, жадность',
    lessons: [
      {
        id: 'ege_re_1', title: 'Поиск по шаблону', xp: 15,
        questions: [
          { type: 'output', q: 'Что выведет программа?', code: "from re import findall\nprint(findall(r'[0-9]+', 'A12B345C6'))", answer: "['12', '345', '6']",
            explain: '[0-9]+ ищет все группы цифр: 12, 345, 6.' },
          { type: 'output', q: 'Сколько групп цифр найдено?', code: "from re import findall\nprint(len(findall(r'[0-9]+', 'a1b22c333')))", answer: '3',
            explain: 'Группы: 1, 22, 333 — три штуки.' },
          { type: 'output', q: 'Что выведет ЖАДНЫЙ шаблон?', code: "from re import findall\nprint(findall(r'<.+>', '<a><b><c>'))", answer: "['<a><b><c>']",
            explain: 'Жадный .+ захватывает максимум — всю строку от первого < до последнего >.' },
          { type: 'output', q: 'Что выведет ЛЕНИВЫЙ шаблон?', code: "from re import findall\nprint(findall(r'<.+?>', '<a><b><c>'))", answer: "['<a>', '<b>', '<c>']",
            explain: 'Ленивый .+? захватывает минимум — каждый тег отдельно.' },
          { type: 'mcq', q: 'Что означает [A-Z] в регулярке?',
            options: ['Одна заглавная буква A–Z', 'Слово из букв', 'Любой символ', 'Ровно A, потом Z'], answer: 0,
            explain: '[A-Z] — один символ из диапазона A до Z.' },
          { type: 'mcq', q: 'Что делает квантификатор + ?',
            options: ['1 и более повторов', '0 и более', 'Ровно 1', 'Ноль или один'], answer: 0,
            explain: '+ означает «один и больше раз».' },
          { type: 'mcq', q: 'Как сделать квантификатор ленивым?',
            options: ['Добавить ? после него', 'Убрать +', 'Добавить *', 'Написать [ ]'], answer: 0,
            explain: '.+? , .*? — знак ? после квантификатора делает его ленивым.' },
          { type: 'bug', q: 'Зачем префикс r перед шаблоном r"[0-9]+"?',
            options: ['Чтобы \\ понимался как символ регулярки, а не Python', 'Для скорости', 'Обязателен всегда', 'Ни за чем'], answer: 0,
            explain: 'r"" (raw-строка) отключает спецобработку \\ Python — важно для регулярок.' },
        ],
      },
    ],
  },

  // ── fnmatch маски (задача 25) ──
  {
    id: 'ege_fnmatch',
    level: 'Продвинутый',
    icon: '🎭',
    color: '#ec4899',
    title: 'Маски fnmatch (задача 25)',
    desc: 'проверка числа по шаблону',
    lessons: [
      {
        id: 'ege_fnmatch_1', title: 'Числа по маске', xp: 15,
        questions: [
          { type: 'output', q: 'Что выведет программа?', code: 'from fnmatch import fnmatch\nprint(fnmatch("54213", "54?1?"))', answer: 'True',
            explain: '? — один любой символ. 54?1? подходит к 54213: 5-4-2-1-3.' },
          { type: 'output', q: 'Что выведет программа?', code: 'from fnmatch import fnmatch\nprint(fnmatch("12700", "1*0"))', answer: 'True',
            explain: '* — любые символы. 1*0: начинается на 1, кончается на 0.' },
          { type: 'output', q: 'Что выведет программа?', code: 'from fnmatch import fnmatch\nprint(fnmatch("12345", "1?345"))', answer: 'True',
            explain: '? заменяет одну цифру: 1-?-3-4-5 = 12345.' },
          { type: 'output', q: 'Что выведет программа?', code: 'from fnmatch import fnmatch\nprint(fnmatch("999", "1*"))', answer: 'False',
            explain: '1* требует, чтобы число начиналось с 1. 999 — нет.' },
          { type: 'mcq', q: 'Что означает ? в маске fnmatch?',
            options: ['Ровно один любой символ', 'Любое число символов', 'Цифру', 'Ничего'], answer: 0,
            explain: '? — ровно один любой символ. * — любое количество.' },
          { type: 'mcq', q: 'Что означает * в маске fnmatch?',
            options: ['Любое количество символов (в т.ч. 0)', 'Ровно один', 'Умножение', 'Только цифры'], answer: 0,
            explain: '* — любое число символов, включая ноль.' },
          { type: 'bug', q: 'Почему fnmatch(12345, "1*") даст ошибку?', code: 'from fnmatch import fnmatch\nprint(fnmatch(12345, "1*"))',
            options: ['fnmatch принимает строки — нужен str(12345)', 'Маска неверна', 'Нет импорта', 'Всё верно'], answer: 0,
            explain: 'fnmatch работает со строками. Число надо превратить: str(12345).' },
          { type: 'assemble', q: 'Собери: проверить число 777 по маске "7*7"',
            lines: ['from fnmatch import fnmatch', 'print(fnmatch("777", "7*7"))'],
            explain: 'Импорт, затем проверка строки по маске.' },
        ],
      },
    ],
  },
];
