// ege_tasks_deep.js — углублённая проработка задач 24, 25, 27 (по совету эксперта).
// Мержится к темам-боссам ege_task24 / ege_task25 / ege_task27.
// Все output-ответы выверены на настоящем Python.

export const DEEP_TASK_LESSONS = {
  // ══════════ ЗАДАЧА 24 ══════════
  ege_task24: [
    {
      id: 'ege_task24_2', title: 'Классы и повторы', xp: 20,
      questions: [
        { type: 'output', q: 'Что выведет программа?', code: "from re import findall\nprint(findall(r'[A-Z]', 'aBcDe'))", answer: "['B', 'D']",
          explain: '[A-Z] — одна заглавная буква. В строке это B и D.' },
        { type: 'output', q: 'Что выведет программа?', code: "from re import findall\nprint(findall(r'[a-z]+', 'AB cd EF gh'))", answer: "['cd', 'gh']",
          explain: '[a-z]+ — группы строчных букв: cd и gh.' },
        { type: 'output', q: 'Что выведет программа?', code: "from re import findall\nprint(findall(r'[0-9]{2}', '123456'))", answer: "['12', '34', '56']",
          explain: '{2} — ровно 2 цифры подряд. Строка режется на пары.' },
        { type: 'output', q: 'Что выведет программа?', code: "from re import findall\nprint(findall(r'[0-9]{2,}', 'a1b22c333'))", answer: "['22', '333']",
          explain: '{2,} — две и больше цифр. Одиночная 1 не подходит.' },
        { type: 'output', q: 'Сколько раз встречается AB?', code: "from re import findall\nprint(len(findall(r'AB', 'ABABAB')))", answer: '3',
          explain: 'AB повторяется трижды.' },
        { type: 'output', q: 'Что выведет программа?', code: "from re import findall\nprint(findall(r'A+', 'AABAAAB'))", answer: "['AA', 'AAA']",
          explain: 'A+ — группы букв A: AA и AAA.' },
        { type: 'output', q: 'Что выведет программа?', code: "from re import findall\nprint(findall(r'[13579]', '123456789'))", answer: "['1', '3', '5', '7', '9']",
          explain: '[13579] — один из нечётных символов.' },
        { type: 'output', q: 'Что выведет программа?', code: "from re import findall\nprint(findall(r'X{3}', 'XXXXX'))", answer: "['XXX']",
          explain: '{3} — ровно 3 подряд. Из 5 иксов выходит одна тройка (остаток короче).' },
        { type: 'mcq', q: 'Что означает [^0-9] в шаблоне?',
          options: ['Любой символ, КРОМЕ цифры', 'Любая цифра', 'Начало строки', 'Ровно 0 или 9'], answer: 0,
          explain: 'Крышка ^ внутри скобок означает «кроме перечисленного».' },
        { type: 'mcq', q: 'Что означает квантификатор {2,5}?',
          options: ['От 2 до 5 повторов', 'Ровно 25', '2 или 5', 'Минимум 5'], answer: 0,
          explain: '{n,m} — от n до m повторов.' },
        { type: 'bug', q: 'Почему шаблон "\\d+" лучше писать как r"\\d+"?',
          options: ['r-строка отдаёт \\ регулярке, а не Python', 'Быстрее', 'Обязательно всегда', 'Ни за чем'], answer: 0,
          explain: 'Без r Python сам обработает \\, и шаблон сломается.' },
      ],
    },
    {
      id: 'ege_task24_3', title: 'Шаблоны задачи 24', xp: 20,
      questions: [
        { type: 'output', q: 'Что выведут позиции совпадений?', code: "from re import finditer\nprint([m.start() for m in finditer(r'[0-9]+', 'a1bb22')])", answer: '[1, 4]',
          explain: 'Первое число на индексе 1, второе на индексе 4.' },
        { type: 'output', q: 'Что выведет программа? (числа без ведущего нуля)', code: "from re import findall\nprint(findall(r'[1-9][0-9]*', '007 12 305'))", answer: "['7', '12', '305']",
          explain: '[1-9] в начале запрещает ноль. Из 007 берётся только 7.' },
        { type: 'mcq', q: 'Как в шаблоне задать «число без ведущего нуля»?',
          options: ['[1-9][0-9]*', '[0-9]+', '0[0-9]*', '[0-9]{2}'], answer: 0,
          explain: 'Первая цифра из [1-9] (не ноль), дальше любые цифры.' },
        { type: 'output', q: 'Что выведет ЖАДНЫЙ шаблон?', code: 'from re import findall\nprint(findall(r\'".*"\', \'"a" "b"\'))', answer: '[\'"a" "b"\']',
          explain: 'Жадный .* тянет от первой кавычки до последней — всё в одном.' },
        { type: 'output', q: 'Что выведет ЛЕНИВЫЙ шаблон?', code: 'from re import findall\nprint(findall(r\'".*?"\', \'"a" "b"\'))', answer: '[\'"a"\', \'"b"\']',
          explain: 'Ленивый .*? берёт минимум — каждая пара кавычек отдельно.' },
        { type: 'output', q: 'Что выведет программа?', code: "from re import findall\nprint(findall(r'[A-Z][a-z]+', 'Hello World'))", answer: "['Hello', 'World']",
          explain: 'Заглавная + строчные: слова с большой буквы.' },
        { type: 'output', q: 'Что выведет search?', code: "from re import search\nprint(search(r'[0-9]+', 'abc123def').group())", answer: '123',
          explain: 'search находит ПЕРВОЕ совпадение и .group() даёт его текст.' },
        { type: 'output', q: 'Что выведет fullmatch?', code: "from re import fullmatch\nprint(bool(fullmatch(r'[01]+', '0110')))", answer: 'True',
          explain: 'fullmatch проверяет, что ВСЯ строка из 0 и 1. Да → True.' },
        { type: 'output', q: 'Что выведет программа?', code: "from re import findall\nprint(findall(r'a.c', 'abc axc a-c'))", answer: "['abc', 'axc', 'a-c']",
          explain: 'Точка . — любой символ между a и c.' },
        { type: 'mcq', q: 'Что означает точка . в регулярке?',
          options: ['Любой один символ', 'Точку', 'Конец строки', 'Цифру'], answer: 0,
          explain: 'Точка совпадает с любым символом (кроме перевода строки).' },
        { type: 'output', q: 'Сколько групп цифр найдено?', code: "from re import findall\nprint(len(findall(r'[0-9]+', 'a1b22c333d4')))", answer: '4',
          explain: 'Группы: 1, 22, 333, 4 — четыре.' },
        { type: 'assemble', q: 'Собери: найти все числа без ведущего нуля в строке s',
          lines: ['from re import findall', 's = "12 007 45"', 'print(findall(r"[1-9][0-9]*", s))'],
          explain: 'Импорт, строка, поиск по шаблону без ведущего нуля.' },
      ],
    },
  ],

  // ══════════ ЗАДАЧА 25 ══════════
  ege_task25: [
    {
      id: 'ege_task25_2', title: 'Делители', xp: 20,
      questions: [
        { type: 'output', q: 'Сколько делителей у 36?', code: 'n = 36\nk = 0\nfor d in range(1, n + 1):\n    if n % d == 0:\n        k += 1\nprint(k)', answer: '9',
          explain: 'Делители 36: 1,2,3,4,6,9,12,18,36 — девять.' },
        { type: 'output', q: 'Сколько делителей у 13? (простое?)', code: 'n = 13\nk = 0\nfor d in range(1, n + 1):\n    if n % d == 0:\n        k += 1\nprint(k)', answer: '2',
          explain: 'У 13 только 1 и 13 — два делителя, значит число простое.' },
        { type: 'output', q: 'Наименьший делитель больше 1 у числа 15?', code: 'n = 15\nfor d in range(2, n + 1):\n    if n % d == 0:\n        print(d)\n        break', answer: '3',
          explain: 'Перебор с 2: 15 не делится на 2, делится на 3. Ответ 3.' },
        { type: 'output', q: 'Наибольший собственный делитель 28?', code: 'n = 28\nfor d in range(2, n + 1):\n    if n % d == 0:\n        print(n // d)\n        break', answer: '14',
          explain: 'Наименьший делитель 2 → парный ему n//2 = 14 наибольший.' },
        { type: 'output', q: 'Сумма всех делителей 6?', code: 'n = 6\ns = 0\nfor d in range(1, n + 1):\n    if n % d == 0:\n        s += d\nprint(s)', answer: '12',
          explain: '1+2+3+6 = 12.' },
        { type: 'mcq', q: 'Почему делители ищут только до √n?',
          options: ['Делители идут парами d и n//d — второй найдётся сам', 'Так короче', 'Случайно', 'До n нельзя'], answer: 0,
          explain: 'Если d ≤ √n делитель, то n//d ≥ √n — тоже делитель. Достаточно дойти до корня.' },
        { type: 'output', q: 'Что выведет граница перебора?', code: 'n = 100\nprint(int(n ** 0.5))', answer: '10',
          explain: '√100 = 10. Перебор делителей идёт range(2, 11).' },
        { type: 'mcq', q: 'Число простое, если у него делителей...',
          options: ['Ровно 2 (1 и само)', 'Ровно 1', 'Больше 2', 'Ноль'], answer: 0,
          explain: 'Простое число делится только на 1 и на себя — два делителя.' },
        { type: 'output', q: 'Делитель, кончающийся на 3, у числа 39?', code: 'n = 39\nfor d in range(2, int(n ** 0.5) + 1):\n    if n % d == 0:\n        if d % 10 == 3:\n            print(d)\n        elif (n // d) % 10 == 3:\n            print(n // d)', answer: '3',
          explain: '39 = 3·13. Делитель 3 кончается на 3.' },
        { type: 'output', q: 'Делитель, кончающийся на 3, у числа 169?', code: 'n = 169\nfor d in range(2, int(n ** 0.5) + 1):\n    if n % d == 0:\n        if d % 10 == 3:\n            print(d)\n        elif (n // d) % 10 == 3:\n            print(n // d)', answer: '13',
          explain: '169 = 13·13. Делитель 13 кончается на 3.' },
        { type: 'bug', q: 'Почему перебор до n (range(2, n+1)) для больших чисел плохо?',
          options: ['Слишком медленно — хватает до √n', 'Даёт ошибку', 'Не находит делители', 'Ничего страшного'], answer: 0,
          explain: 'До n — миллиарды шагов. До √n в разы быстрее и достаточно.' },
        { type: 'output', q: 'Сколько делителей у 1?', code: 'n = 1\nk = 0\nfor d in range(1, n + 1):\n    if n % d == 0:\n        k += 1\nprint(k)', answer: '1',
          explain: 'У единицы один делитель — она сама.' },
      ],
    },
    {
      id: 'ege_task25_3', title: 'Маски чисел', xp: 20,
      questions: [
        { type: 'output', q: 'Что выведет программа?', code: 'from fnmatch import fnmatch\nprint(fnmatch("707", "7?7"))', answer: 'True',
          explain: '7-?-7: 7, любой (0), 7. Подходит.' },
        { type: 'output', q: 'Что выведет программа?', code: 'from fnmatch import fnmatch\nprint(fnmatch("189", "1*9"))', answer: 'True',
          explain: '1, потом что угодно (8), в конце 9. Подходит.' },
        { type: 'output', q: 'Что выведет программа?', code: 'from fnmatch import fnmatch\nprint(fnmatch("125", "??5"))', answer: 'True',
          explain: 'Два любых символа и 5 в конце. 125 подходит.' },
        { type: 'output', q: 'Что выведет программа?', code: 'from fnmatch import fnmatch\nprint(fnmatch("130", "3*"))', answer: 'False',
          explain: '3* требует, чтобы число начиналось с 3. 130 начинается с 1.' },
        { type: 'output', q: 'Что выведет программа? (класс символов)', code: 'from fnmatch import fnmatch\nprint(fnmatch("25", "[24]5"))', answer: 'True',
          explain: '[24] — 2 или 4 на первом месте. 25 начинается с 2 — подходит.' },
        { type: 'output', q: 'Что выведет программа?', code: 'from fnmatch import fnmatch\nprint(fnmatch("35", "[24]5"))', answer: 'False',
          explain: '35 начинается с 3, а нужно 2 или 4 — не подходит.' },
        { type: 'output', q: 'Какие кратные 7 из 100..200 подходят под маску «1?2»?', code: 'from fnmatch import fnmatch\nres = []\nfor n in range(105, 201, 7):\n    if fnmatch(str(n), "1?2"):\n        res.append(n)\nprint(res)', answer: '[112, 182]',
          explain: '112 (1-1-2) и 182 (1-8-2) — кратны 7 и подходят под маску.' },
        { type: 'mcq', q: 'Чем ? отличается от * в маске?',
          options: ['? — один символ, * — любое количество', 'Ничем', '? — цифра, * — буква', '? — начало, * — конец'], answer: 0,
          explain: '? заменяет ровно один символ, * — любое число символов.' },
        { type: 'bug', q: 'Почему fnmatch(707, "7?7") даст ошибку?', code: 'from fnmatch import fnmatch\nprint(fnmatch(707, "7?7"))',
          options: ['Нужна строка: str(707)', 'Маска неверна', 'Нет импорта', 'Всё верно'], answer: 0,
          explain: 'fnmatch работает только со строками. Число оборачивают в str().' },
        { type: 'mcq', q: 'Что означает [135] в маске fnmatch?',
          options: ['Один из символов 1, 3 или 5', 'Число 135', 'Три любых символа', 'От 1 до 5'], answer: 0,
          explain: '[135] — один символ из перечисленных: 1, 3 или 5.' },
        { type: 'output', q: 'Сумма цифр числа 253?', code: 'n = 253\ns = 0\nfor c in str(n):\n    s += int(c)\nprint(s)', answer: '10',
          explain: 'Превращаем в строку, перебираем цифры: 2+5+3 = 10.' },
        { type: 'assemble', q: 'Собери шаблон задачи 25: первые числа под маску',
          lines: ['from fnmatch import fnmatch', 'for n in range(100, 1000):', '    if fnmatch(str(n), "1?7"):', '        print(n)'],
          explain: 'Перебор, проверка маски строки числа.' },
      ],
    },
  ],

  // ══════════ ЗАДАЧА 27 ══════════
  ege_task27: [
    {
      id: 'ege_task27_2', title: 'Расстояния', xp: 20,
      questions: [
        { type: 'output', q: 'Расстояние между точками?', code: 'from math import dist\nprint(dist([0, 0], [8, 15]))', answer: '17.0',
          explain: '√(8²+15²) = √289 = 17.0. Тройка 8-15-17.' },
        { type: 'output', q: 'Расстояние между точками?', code: 'from math import dist\nprint(dist([0, 0], [9, 12]))', answer: '15.0',
          explain: '√(9²+12²) = √225 = 15.0.' },
        { type: 'output', q: 'Расстояние между точками?', code: 'from math import dist\nprint(dist([0, 0], [20, 21]))', answer: '29.0',
          explain: '√(20²+21²) = √841 = 29.0.' },
        { type: 'output', q: 'Расстояние между точками?', code: 'from math import dist\nprint(dist([1, 2], [4, 6]))', answer: '5.0',
          explain: '√(3²+4²) = 5.0. Разности 3 и 4.' },
        { type: 'output', q: 'Расстояние точки самой до себя?', code: 'from math import dist\nprint(dist([2, 3], [2, 3]))', answer: '0.0',
          explain: 'Одинаковые точки — расстояние 0.0.' },
        { type: 'output', q: 'Своя формула расстояния (без math)?', code: 'a = [0, 0]\nb = [5, 12]\nprint(((b[0] - a[0]) ** 2 + (b[1] - a[1]) ** 2) ** 0.5)', answer: '13.0',
          explain: 'Теорема Пифагора вручную: √(25+144) = 13.0.' },
        { type: 'output', q: 'Максимальное расстояние от (0,0)?', code: 'from math import dist\npts = [[0, 0], [3, 4], [8, 6], [1, 1]]\nprint(round(max(dist([0, 0], p) for p in pts), 2))', answer: '10.0',
          explain: 'Самая далёкая точка (8,6): √(64+36)=10.0.' },
        { type: 'output', q: 'Округление √2 до 2 знаков?', code: 'from math import dist\nprint(f"{dist([0, 0], [1, 1]):.2f}")', answer: '1.41',
          explain: '√2 ≈ 1.4142, округляем до 1.41.' },
        { type: 'output', q: 'Сумма расстояний от (0,0) до двух точек?', code: 'from math import dist\npts = [[3, 4], [6, 8]]\nprint(round(sum(dist([0, 0], p) for p in pts), 1))', answer: '15.0',
          explain: '5.0 + 10.0 = 15.0.' },
        { type: 'mcq', q: 'По какой формуле считают расстояние на плоскости?',
          options: ['√((x2-x1)² + (y2-y1)²)', '(x2-x1)+(y2-y1)', 'x1·x2 + y1·y2', '(x2+x1)/2'], answer: 0,
          explain: 'Теорема Пифагора для разностей координат.' },
        { type: 'mcq', q: 'Что удобнее — своя dist или math.dist?',
          options: ['math.dist — готовая, если разрешена', 'Только своя', 'Они разные', 'math.dist медленнее'], answer: 0,
          explain: 'math.dist([x1,y1],[x2,y2]) сразу даёт расстояние. Своя нужна, если нельзя импорт.' },
      ],
    },
    {
      id: 'ege_task27_3', title: 'Кластеры и центр', xp: 20,
      questions: [
        { type: 'output', q: 'Центр кластера (медоид)?', code: 'from math import dist\npts = [[0, 0], [3, 4], [6, 8]]\nbest = min(pts, key=lambda p: sum(dist(p, q) for q in pts))\nprint(best)', answer: '[3, 4]',
          explain: 'Медоид — точка с наименьшей суммой расстояний до остальных. Это [3, 4].' },
        { type: 'output', q: 'Сколько точек в радиусе 5 от (0,0)?', code: 'from math import dist\npts = [[1, 1], [3, 4], [5, 5], [0, 4]]\nk = 0\nfor p in pts:\n    if dist([0, 0], p) <= 5:\n        k += 1\nprint(k)', answer: '3',
          explain: '(1,1),(3,4),(0,4) в радиусе 5; (5,5) дальше. Итого 3.' },
        { type: 'output', q: 'Минимальное расстояние между парами точек?', code: 'from math import dist\npts = [[0, 0], [3, 4], [8, 6], [1, 1]]\nmn = 10 ** 9\nfor i in range(len(pts)):\n    for j in range(i + 1, len(pts)):\n        d = dist(pts[i], pts[j])\n        if d < mn:\n            mn = d\nprint(round(mn, 2))', answer: '1.41',
          explain: 'Ближайшая пара (0,0) и (1,1): √2 ≈ 1.41.' },
        { type: 'mcq', q: 'Что такое медоид кластера?',
          options: ['Точка с мин. суммой расстояний до остальных', 'Средняя координата', 'Первая точка', 'Самая дальняя'], answer: 0,
          explain: 'Медоид — «самая центральная» реальная точка кластера.' },
        { type: 'mcq', q: 'Как в задаче 27 читают координаты точек из файла?',
          options: ['[int(x) for x in line.split()] для каждой строки', 'input()', 'readline() один раз', 'через fnmatch'], answer: 0,
          explain: 'Каждая строка файла — координаты точки, режем split() и в int.' },
        { type: 'mcq', q: 'Зачем round(d, 2) или f"{d:.2f}" в ответе задачи 27?',
          options: ['Ответ просят с 2 знаками после запятой', 'Для скорости', 'Перевести в двоичное', 'Ни за чем'], answer: 0,
          explain: 'Расстояния дробные, ответ округляют до сотых.' },
        { type: 'output', q: 'Ближайшая к (0,0) точка?', code: 'from math import dist\npts = [[5, 5], [1, 2], [3, 4]]\nbest = min(pts, key=lambda p: dist([0, 0], p))\nprint(best)', answer: '[1, 2]',
          explain: 'min с ключом-расстоянием: ближайшая (1,2), √5 ≈ 2.24.' },
        { type: 'output', q: 'Самая дальняя от (0,0) точка?', code: 'from math import dist\npts = [[5, 5], [1, 2], [3, 4]]\nbest = max(pts, key=lambda p: dist([0, 0], p))\nprint(best)', answer: '[5, 5]',
          explain: 'max с ключом-расстоянием: дальше всех (5,5), √50 ≈ 7.07.' },
        { type: 'bug', q: 'Почему во вложенном переборе пар пишут range(i+1, n)?',
          options: ['Чтобы не сравнивать точку с собой и не дублировать пары', 'Так быстрее пишется', 'Иначе ошибка', 'Без разницы'], answer: 0,
          explain: 'j начинается с i+1 — каждая пара берётся один раз, без (i,i).' },
        { type: 'assemble', q: 'Собери: расстояние от (0,0) до (6,8) через math.dist',
          lines: ['from math import dist', 'print(dist([0, 0], [6, 8]))'],
          explain: 'Импорт dist, вызов с двумя точками.' },
      ],
    },
  ],
};
