// ege_libs2.js — библиотеки для ЕГЭ (глава 15). Партия 2.
// f-строки и файлы, сети, геометрия, Черепаха.

export const EGE_LIB_UNITS_2 = [
  // ── f-строки и файлы (задачи 9, 13, 17, 24, 27) ──
  {
    id: 'ege_files',
    level: 'Продвинутый',
    icon: '📄',
    color: '#f59e0b',
    title: 'Файлы и f-строки',
    desc: 'чтение файла, форматирование',
    lessons: [
      {
        id: 'ege_files_1', title: 'f-строки', xp: 15,
        questions: [
          { type: 'output', q: 'Что выведет программа?', code: 'x = 42\nprint(f"ответ {x}")', answer: 'ответ 42',
            explain: 'f-строка подставляет значение переменной внутри {}.' },
          { type: 'output', q: 'Что выведет программа? (двоичное с нулями)', code: 'x = 5\nprint(f"{x:08b}")', answer: '00000101',
            explain: '{x:08b} — двоичная запись, дополненная нулями до 8 знаков.' },
          { type: 'output', q: 'Что выведет программа? (16-ричное)', code: 'x = 255\nprint(f"{x:x}")', answer: 'ff',
            explain: '{x:x} — шестнадцатеричная запись. 255 = ff.' },
          { type: 'output', q: 'Что выведет программа? (8-ричное)', code: 'x = 8\nprint(f"{x:o}")', answer: '10',
            explain: '{x:o} — восьмеричная запись. 8 в 8-ричной = 10.' },
          { type: 'output', q: 'Что выведет программа? (2 знака после запятой)', code: 'x = 3.14159\nprint(f"{x:.2f}")', answer: '3.14',
            explain: '{x:.2f} округляет до 2 знаков — важно в задаче 27.' },
          { type: 'mcq', q: 'Что делает f"{x:032b}" (задача 13, IP)?',
            options: ['32-битная двоичная запись с нулями', 'Умножает на 32', 'Округляет', 'Шестнадцатеричная'], answer: 0,
            explain: '{x:032b} — двоичная запись длиной 32 бита, для IP-адресов.' },
          { type: 'assemble', q: 'Собери: вывести число 10 в двоичном виде на 4 знака',
            lines: ['x = 10', 'print(f"{x:04b}")'],
            explain: '{x:04b} — двоичное, дополненное нулями до 4 знаков.' },
        ],
      },
      {
        id: 'ege_files_2', title: 'Чтение из файла', xp: 15,
        questions: [
          { type: 'mcq', q: 'Как считать по одному числу в строке (задачи 9, 17)?',
            options: ['[int(x) for x in open("f.txt")]', 'read(f.txt)', 'input("f.txt")', 'file.numbers()'], answer: 0,
            explain: 'Генератор [int(x) for x in open(...)] читает по числу из каждой строки.' },
          { type: 'mcq', q: 'Как разбить строку файла на числа через пробел?',
            options: ['[int(x) for x in line.split()]', 'line.numbers()', 'int(line)', 'line / " "'], answer: 0,
            explain: 'line.split() режет по пробелам, int превращает в числа.' },
          { type: 'mcq', q: 'Как прочитать одну гигантскую строку (задача 24)?',
            options: ['open("f.txt").readline()', 'open("f.txt").number()', 'read.line()', 'input()'], answer: 0,
            explain: 'readline() читает одну строку целиком — для регулярок в задаче 24.' },
          { type: 'output', q: 'Что выведет генератор чисел из строки?', code: 's = "3 7 2 8"\na = [int(x) for x in s.split()]\nprint(sum(a))', answer: '20',
            explain: 'split даёт ["3","7","2","8"], int — числа, сумма 3+7+2+8=20.' },
          { type: 'output', q: 'Что выведет программа? (максимум из строки чисел)', code: 's = "5 12 3 8"\na = [int(x) for x in s.split()]\nprint(max(a))', answer: '12',
            explain: 'Числа 5,12,3,8, максимум 12.' },
          { type: 'mcq', q: 'Что делает [int(x) for x in s.split()]?',
            options: ['Превращает строку чисел в список int', 'Складывает', 'Сортирует', 'Считает длину'], answer: 0,
            explain: 'Это генератор списка: режем строку и превращаем каждый кусок в число.' },
        ],
      },
    ],
  },

  // ── ipaddress (задача 13) ──
  {
    id: 'ege_ipaddress',
    level: 'Продвинутый',
    icon: '🌐',
    color: '#f59e0b',
    title: 'Сети ipaddress (задача 13)',
    desc: 'ip_network, адрес сети, маска',
    lessons: [
      {
        id: 'ege_ipaddress_1', title: 'IP-адреса и сети', xp: 15,
        questions: [
          { type: 'output', q: 'Что выведет программа? (адрес сети)', code: "from ipaddress import ip_network\nnet = ip_network('192.168.1.10/255.255.255.0', strict=False)\nprint(net[0])", answer: '192.168.1.0',
            explain: 'net[0] — адрес сети (первый адрес диапазона).' },
          { type: 'output', q: 'Что выведет программа? (broadcast)', code: "from ipaddress import ip_network\nnet = ip_network('192.168.1.10/255.255.255.0', strict=False)\nprint(net[-1])", answer: '192.168.1.255',
            explain: 'net[-1] — широковещательный адрес (последний).' },
          { type: 'output', q: 'Что выведет программа? (всего адресов)', code: "from ipaddress import ip_network\nnet = ip_network('10.0.0.0/255.255.255.0', strict=False)\nprint(net.num_addresses)", answer: '256',
            explain: 'Маска .0 оставляет 8 бит на узлы: 2^8 = 256 адресов.' },
          { type: 'output', q: 'Что выведет программа? (маска)', code: "from ipaddress import ip_network\nnet = ip_network('192.168.0.0/24', strict=False)\nprint(net.netmask)", answer: '255.255.255.0',
            explain: '/24 — это 24 единицы в маске = 255.255.255.0.' },
          { type: 'mcq', q: 'Что вернёт net[-2]?',
            options: ['Максимальный адрес для компьютера', 'Адрес сети', 'Маску', 'Broadcast'], answer: 0,
            explain: 'net[-2] — самый большой адрес узла (перед broadcast).' },
          { type: 'mcq', q: 'Зачем нужен strict=False?',
            options: ['Иначе ошибка на адресе узла, а не сети', 'Для скорости', 'Ни за чем', 'Меняет маску'], answer: 0,
            explain: 'Без strict=False Python требует адрес самой сети. С ним — принимает любой адрес.' },
          { type: 'mcq', q: 'Как посчитать число узлов сети?',
            options: ['num_addresses - 2', 'num_addresses', 'netmask', 'net[0]'], answer: 0,
            explain: 'Минус адрес сети и broadcast: num_addresses - 2.' },
        ],
      },
    ],
  },

  // ── геометрия / расстояния (задача 27) ──
  {
    id: 'ege_geometry',
    level: 'Продвинутый',
    icon: '📏',
    color: '#ec4899',
    title: 'Геометрия (задача 27)',
    desc: 'расстояние между точками, dist',
    lessons: [
      {
        id: 'ege_geometry_1', title: 'Расстояние и центр', xp: 15,
        questions: [
          { type: 'output', q: 'Что выведет программа? (расстояние 3-4-5)', code: 'def dist(a, b):\n    return ((b[0] - a[0]) ** 2 + (b[1] - a[1]) ** 2) ** 0.5\nprint(dist([0, 0], [3, 4]))', answer: '5.0',
            explain: 'По теореме Пифагора: √(3² + 4²) = √25 = 5.0.' },
          { type: 'output', q: 'Что выведет встроенная math.dist?', code: 'from math import dist\nprint(dist([0, 0], [3, 4]))', answer: '5.0',
            explain: 'math.dist — готовая функция расстояния. Тот же результат 5.0.' },
          { type: 'output', q: 'Что выведет программа?', code: 'from math import dist\nprint(dist([1, 1], [4, 5]))', answer: '5.0',
            explain: '√((4-1)² + (5-1)²) = √(9+16) = √25 = 5.0.' },
          { type: 'output', q: 'Что выведет программа? (округление)', code: 'from math import dist\nd = dist([0, 0], [1, 1])\nprint(f"{d:.2f}")', answer: '1.41',
            explain: '√2 ≈ 1.4142, округляем до 1.41.' },
          { type: 'mcq', q: 'По какой формуле считается расстояние в задаче 27?',
            options: ['√((x2-x1)² + (y2-y1)²)', 'x2-x1 + y2-y1', '(x2+x1)/2', 'x1·y2'], answer: 0,
            explain: 'Это теорема Пифагора — расстояние между точками на плоскости.' },
          { type: 'mcq', q: 'Что такое медоид (центр кластера) в задаче 27?',
            options: ['Точка с минимальной суммой расстояний до остальных', 'Самая левая точка', 'Среднее арифметика', 'Первая точка'], answer: 0,
            explain: 'Медоид — точка кластера, ближайшая ко всем остальным (мин. сумма расстояний).' },
          { type: 'assemble', q: 'Собери функцию расстояния через math.dist',
            lines: ['from math import dist', 'print(dist([0, 0], [6, 8]))'],
            explain: 'Импорт dist, вызов с двумя точками.' },
        ],
      },
    ],
  },

  // ── turtle (задача 6) — только концептуально ──
  {
    id: 'ege_turtle',
    level: 'Продвинутый',
    icon: '🐢',
    color: '#4ade80',
    title: 'Черепаха turtle (задача 6)',
    desc: 'рисование фигуры и сетка точек',
    lessons: [
      {
        id: 'ege_turtle_1', title: 'Исполнитель Черепаха', xp: 15,
        questions: [
          { type: 'mcq', q: 'Что делает fd(n) в turtle?',
            options: ['Двигает вперёд на n', 'Поворот', 'Ставит точку', 'Назад'], answer: 0,
            explain: 'fd(n) (forward) — вперёд на n шагов.' },
          { type: 'mcq', q: 'Что делает rt(90)?',
            options: ['Поворот направо на 90°', 'Вперёд на 90', 'Точку', 'Влево'], answer: 0,
            explain: 'rt(угол) (right) — поворот направо на угол в градусах.' },
          { type: 'mcq', q: 'Зачем up() перед расстановкой точек?',
            options: ['Поднять перо — двигаться без рисования', 'Ускорить', 'Закрасить', 'Повернуть'], answer: 0,
            explain: 'up() (penup) поднимает перо: Черепаха ходит, но не оставляет линий.' },
          { type: 'mcq', q: 'Зачем tracer(0) и update()?',
            options: ['Отключить анимацию и показать сразу — рисует мгновенно', 'Замедлить', 'Стереть', 'Повернуть'], answer: 0,
            explain: 'tracer(0) выключает анимацию, update() показывает результат — иначе долго.' },
          { type: 'mcq', q: 'Как решают задачу 6 с Черепахой?',
            options: ['Рисуют фигуру, засыпают экран точками сетки, считают точки внутри', 'Считают формулой', 'Гадают', 'Через input'], answer: 0,
            explain: 'Python рисует фигуру и сетку красных точек — считаешь точки внутри фигуры глазами.' },
          { type: 'mcq', q: 'Что ставит dot(3, "red")?',
            options: ['Красную точку размером 3', 'Линию', 'Поворот', 'Число 3'], answer: 0,
            explain: 'dot(размер, цвет) ставит точку заданного размера и цвета.' },
        ],
      },
    ],
  },
];
