// oge.js — программа уровня ОГЭ: от вывода до строк.
// Типы вопросов:
//   mcq      — { type, q, code?, options:[...], answer:index, explain }
//   output   — { type, q, code, answer:"...", accept?:[...], explain }
//   assemble — { type, q, lines:[...в правильном порядке...], explain }

export const OGE_UNITS = [
  // ── Юнит 1 ────────────────────────────────
  {
    id: 'oge_print',
    level: 'ОГЭ',
    icon: '🖥️',
    color: '#4ade80',
    title: 'Первые шаги',
    desc: 'Вывод на экран, комментарии',
    lessons: [
      {
        id: 'oge_print_1',
        title: 'Команда print',
        xp: 10,
        questions: [
          { type: 'mcq', q: 'Какая команда выводит текст на экран?',
            options: ['print', 'input', 'echo', 'show'], answer: 0,
            explain: 'print() — выводит значение на экран. input() наоборот считывает ввод.' },
          { type: 'output', q: 'Что выведет программа?', code: 'print("Привет")',
            answer: 'Привет',
            explain: 'print печатает текст внутри кавычек без самих кавычек.' },
          { type: 'output', q: 'Что выведет программа?', code: 'print(2 + 3)',
            answer: '5',
            explain: 'Без кавычек 2 + 3 — это математика, результат 5.' },
          { type: 'mcq', q: 'Что выведет print("2" + "3")?',
            code: 'print("2" + "3")',
            options: ['5', '23', '"23"', 'ошибка'], answer: 1,
            explain: 'В кавычках это строки. Плюс для строк — склейка: "2"+"3" = "23".' },
          { type: 'assemble', q: 'Собери программу, которая выведет слово Кот',
            lines: ['print("Кот")'],
            explain: 'Одна строка: print("Кот").' },
        ],
      },
      {
        id: 'oge_print_2',
        title: 'Несколько строк',
        xp: 10,
        questions: [
          { type: 'output', q: 'Что выведет программа?',
            code: 'print("раз")\nprint("два")',
            answer: 'раз\nдва',
            explain: 'Каждый print печатает с новой строки.' },
          { type: 'mcq', q: 'Как напечатать два слова в одной строке через пробел?',
            options: ['print("a", "b")', 'print("a" "b")', 'print("a"; "b")', 'print("a"+"b")'],
            answer: 0,
            explain: 'print("a", "b") печатает "a b" — запятая ставит пробел между значениями.' },
          { type: 'output', q: 'Что выведет программа?',
            code: 'print("Ответ:", 42)',
            answer: 'Ответ: 42',
            explain: 'Запятая в print добавляет пробел между "Ответ:" и 42.' },
          { type: 'mcq', q: 'Что делает символ # в строке кода?',
            options: ['Начинает комментарий', 'Умножает', 'Выводит текст', 'Создаёт переменную'],
            answer: 0,
            explain: '# — комментарий. Всё после него Python игнорирует.' },
        ],
      },
    ],
  },

  // ── Юнит 2 ────────────────────────────────
  {
    id: 'oge_vars',
    level: 'ОГЭ',
    icon: '📦',
    color: '#4ade80',
    title: 'Переменные',
    desc: 'Хранение значений, типы данных',
    lessons: [
      {
        id: 'oge_vars_1',
        title: 'Что такое переменная',
        xp: 10,
        questions: [
          { type: 'output', q: 'Что выведет программа?',
            code: 'x = 5\nprint(x)',
            answer: '5',
            explain: 'x = 5 кладёт в переменную x число 5. print(x) выводит его.' },
          { type: 'output', q: 'Что выведет программа?',
            code: 'a = 3\nb = 4\nprint(a + b)',
            answer: '7',
            explain: 'a = 3, b = 4, значит a + b = 7.' },
          { type: 'output', q: 'Что выведет программа?',
            code: 'x = 5\nx = 10\nprint(x)',
            answer: '10',
            explain: 'Второе присваивание перезаписывает: теперь x = 10.' },
          { type: 'mcq', q: 'Какое имя переменной НЕ разрешено в Python?',
            options: ['my_var', 'x2', '2x', 'name'], answer: 2,
            explain: 'Имя не может начинаться с цифры: 2x — ошибка.' },
          { type: 'assemble', q: 'Собери: положи в x число 7 и выведи его',
            lines: ['x = 7', 'print(x)'],
            explain: 'Сначала создаём переменную, потом выводим.' },
        ],
      },
      {
        id: 'oge_vars_2',
        title: 'Числа и строки',
        xp: 10,
        questions: [
          { type: 'mcq', q: 'Какого типа значение "123" (в кавычках)?',
            options: ['Число', 'Строка', 'Переменная', 'Список'], answer: 1,
            explain: 'В кавычках — всегда строка (str), даже если внутри цифры.' },
          { type: 'output', q: 'Что выведет программа?',
            code: 'x = 10\ny = 3\nprint(x * y)',
            answer: '30',
            explain: 'x * y = 10 * 3 = 30.' },
          { type: 'mcq', q: 'Что выведет print(type(5))?',
            options: ["<class 'int'>", "<class 'str'>", '5', "<class 'float'>"], answer: 0,
            explain: '5 — целое число, его тип int.' },
          { type: 'output', q: 'Что выведет программа?',
            code: 'name = "Аня"\nprint("Привет, " + name)',
            answer: 'Привет, Аня',
            explain: 'Склейка строк: "Привет, " + "Аня".' },
        ],
      },
    ],
  },

  // ── Юнит 3 ────────────────────────────────
  {
    id: 'oge_input',
    level: 'ОГЭ',
    icon: '⌨️',
    color: '#4ade80',
    title: 'Ввод данных',
    desc: 'input, преобразование типов',
    lessons: [
      {
        id: 'oge_input_1',
        title: 'Команда input',
        xp: 10,
        questions: [
          { type: 'mcq', q: 'Что возвращает input()?',
            options: ['Число', 'Строку', 'Список', 'Ничего'], answer: 1,
            explain: 'input() всегда возвращает строку, даже если ввели цифры.' },
          { type: 'mcq', q: 'Как считать целое число с клавиатуры?',
            options: ['x = input()', 'x = int(input())', 'x = number(input())', 'x = int(x)'],
            answer: 1,
            explain: 'int(input()) — считать строку и превратить в целое число.' },
          { type: 'mcq', q: 'Ввели 5, программа: x = input(); print(x + x). Что выведет?',
            code: 'x = input()   # ввели 5\nprint(x + x)',
            options: ['10', '55', '25', 'ошибка'], answer: 1,
            explain: 'x — строка "5". "5"+"5" = "55" (склейка, не сложение).' },
          { type: 'mcq', q: 'Ввели 5. x = int(input()); print(x + x). Что выведет?',
            code: 'x = int(input())  # ввели 5\nprint(x + x)',
            options: ['10', '55', '25', 'ошибка'], answer: 0,
            explain: 'Теперь x — число 5. 5 + 5 = 10.' },
          { type: 'assemble', q: 'Собери: считай число и выведи его квадрат',
            lines: ['x = int(input())', 'print(x * x)'],
            explain: 'Считываем как int, затем умножаем само на себя.' },
        ],
      },
    ],
  },

  // ── Юнит 4 ────────────────────────────────
  {
    id: 'oge_math',
    level: 'ОГЭ',
    icon: '➗',
    color: '#4ade80',
    title: 'Арифметика',
    desc: 'Операции, деление, остаток',
    lessons: [
      {
        id: 'oge_math_1',
        title: 'Деление и остаток',
        xp: 10,
        questions: [
          { type: 'output', q: 'Что выведет программа?', code: 'print(17 // 5)',
            answer: '3',
            explain: '// — целочисленное деление. 17 // 5 = 3 (без остатка).' },
          { type: 'output', q: 'Что выведет программа?', code: 'print(17 % 5)',
            answer: '2',
            explain: '% — остаток от деления. 17 = 5*3 + 2, остаток 2.' },
          { type: 'output', q: 'Что выведет программа?', code: 'print(2 ** 10)',
            answer: '1024',
            explain: '** — возведение в степень. 2 в 10-й = 1024.' },
          { type: 'mcq', q: 'Как проверить, что число x чётное?',
            options: ['x // 2 == 0', 'x % 2 == 0', 'x / 2 == 0', 'x ** 2 == 0'], answer: 1,
            explain: 'Чётное = делится на 2 без остатка: x % 2 == 0.' },
          { type: 'output', q: 'Что выведет программа?', code: 'print(7 / 2)',
            answer: '3.5',
            explain: 'Один слэш / — обычное деление, результат дробный: 3.5.' },
        ],
      },
    ],
  },

  // ── Юнит 5 ────────────────────────────────
  {
    id: 'oge_if',
    level: 'ОГЭ',
    icon: '🔀',
    color: '#22d3ee',
    title: 'Условия',
    desc: 'if, elif, else, сравнения',
    lessons: [
      {
        id: 'oge_if_1',
        title: 'Ветвление if-else',
        xp: 10,
        questions: [
          { type: 'output', q: 'Что выведет программа?',
            code: 'x = 7\nif x > 5:\n    print("много")\nelse:\n    print("мало")',
            answer: 'много',
            explain: '7 > 5 истинно, поэтому выполнится ветка if.' },
          { type: 'output', q: 'Что выведет программа?',
            code: 'x = 3\nif x > 5:\n    print("много")\nelse:\n    print("мало")',
            answer: 'мало',
            explain: '3 > 5 ложно, поэтому выполнится ветка else.' },
          { type: 'mcq', q: 'Какой оператор проверяет равенство?',
            options: ['=', '==', '=>', 'is='], answer: 1,
            explain: 'Один = присваивает. Два == сравнивают на равенство.' },
          { type: 'output', q: 'Что выведет программа?',
            code: 'x = 10\nif x % 2 == 0:\n    print("чёт")\nelse:\n    print("нечёт")',
            answer: 'чёт',
            explain: '10 % 2 == 0 истинно — число чётное.' },
          { type: 'assemble', q: 'Собери: если a больше 0 — вывести "плюс"',
            lines: ['a = 5', 'if a > 0:', '    print("плюс")'],
            explain: 'После двоеточия тело if пишется с отступом.' },
        ],
      },
      {
        id: 'oge_if_2',
        title: 'Несколько условий',
        xp: 10,
        questions: [
          { type: 'output', q: 'Что выведет программа?',
            code: 'x = 0\nif x > 0:\n    print("плюс")\nelif x < 0:\n    print("минус")\nelse:\n    print("ноль")',
            answer: 'ноль',
            explain: 'x не больше 0 и не меньше 0, значит сработает else.' },
          { type: 'mcq', q: 'Что означает elif?',
            options: ['Конец программы', 'Иначе если', 'Цикл', 'Ошибка'], answer: 1,
            explain: 'elif = "else if" — проверить другое условие, если предыдущее ложно.' },
          { type: 'output', q: 'Что выведет программа?',
            code: 'a = 5\nb = 8\nif a > b:\n    print(a)\nelse:\n    print(b)',
            answer: '8',
            explain: 'Программа выводит большее из двух чисел. 8 > 5.' },
          { type: 'mcq', q: 'Как записать "x больше 3 И меньше 10"?',
            options: ['3 < x < 10', 'x > 3 or x < 10', 'x > 3 & x < 10', '3 < x and 10'],
            answer: 0,
            explain: 'В Python можно писать 3 < x < 10, либо x > 3 and x < 10.' },
        ],
      },
    ],
  },

  // ── Юнит 6 ────────────────────────────────
  {
    id: 'oge_while',
    level: 'ОГЭ',
    icon: '🔁',
    color: '#22d3ee',
    title: 'Цикл while',
    desc: 'Повтор пока условие истинно',
    lessons: [
      {
        id: 'oge_while_1',
        title: 'Пока верно — повторяй',
        xp: 10,
        questions: [
          { type: 'output', q: 'Что выведет программа?',
            code: 'i = 1\nwhile i <= 3:\n    print(i)\n    i = i + 1',
            answer: '1\n2\n3',
            explain: 'Цикл повторяется пока i <= 3, печатая 1, 2, 3.' },
          { type: 'mcq', q: 'Что произойдёт, если забыть i = i + 1 внутри while?',
            options: ['Цикл не запустится', 'Бесконечный цикл', 'Выведет один раз', 'Ошибка'],
            answer: 1,
            explain: 'Без изменения i условие всегда истинно — цикл никогда не кончится.' },
          { type: 'output', q: 'Что выведет программа?',
            code: 's = 0\ni = 1\nwhile i <= 4:\n    s = s + i\n    i = i + 1\nprint(s)',
            answer: '10',
            explain: 'Сумма 1+2+3+4 = 10.' },
          { type: 'assemble', q: 'Собери: вывести числа от 1 до 2 через while',
            lines: ['i = 1', 'while i <= 2:', '    print(i)', '    i = i + 1'],
            explain: 'Счётчик i, условие, тело с печатью и увеличением.' },
        ],
      },
    ],
  },

  // ── Юнит 7 ────────────────────────────────
  {
    id: 'oge_for',
    level: 'ОГЭ',
    icon: '🔂',
    color: '#22d3ee',
    title: 'Цикл for и range',
    desc: 'Перебор диапазона',
    lessons: [
      {
        id: 'oge_for_1',
        title: 'for и range',
        xp: 10,
        questions: [
          { type: 'output', q: 'Что выведет программа?',
            code: 'for i in range(3):\n    print(i)',
            answer: '0\n1\n2',
            explain: 'range(3) даёт 0, 1, 2 — счёт с нуля, тройка не входит.' },
          { type: 'mcq', q: 'Сколько раз выполнится цикл for i in range(5)?',
            options: ['4', '5', '6', '0'], answer: 1,
            explain: 'range(5) = 0,1,2,3,4 — ровно 5 значений.' },
          { type: 'output', q: 'Что выведет программа?',
            code: 'for i in range(1, 4):\n    print(i)',
            answer: '1\n2\n3',
            explain: 'range(1, 4) = 1, 2, 3. Правая граница 4 не входит.' },
          { type: 'output', q: 'Что выведет программа?',
            code: 'for i in range(0, 10, 2):\n    print(i)',
            answer: '0\n2\n4\n6\n8',
            explain: 'Третий аргумент — шаг 2. Идём 0,2,4,6,8.' },
          { type: 'output', q: 'Что выведет программа?',
            code: 's = 0\nfor i in range(1, 5):\n    s = s + i\nprint(s)',
            answer: '10',
            explain: 'Сумма 1+2+3+4 = 10.' },
          { type: 'assemble', q: 'Собери: вывести числа 0,1,2,3,4',
            lines: ['for i in range(5):', '    print(i)'],
            explain: 'range(5) даёт пять чисел от 0 до 4.' },
        ],
      },
      {
        id: 'oge_for_2',
        title: 'range с шагом',
        xp: 10,
        questions: [
          { type: 'output', q: 'Что выведет программа?',
            code: 'for i in range(5, 0, -1):\n    print(i)',
            answer: '5\n4\n3\n2\n1',
            explain: 'Шаг -1 идёт вниз: 5,4,3,2,1. Ноль не входит.' },
          { type: 'mcq', q: 'Что даст range(2, 11, 3)?',
            options: ['2, 5, 8', '2, 5, 8, 11', '2, 4, 6, 8, 10', '3, 6, 9'], answer: 0,
            explain: 'Старт 2, шаг 3: 2, 5, 8. Следующее 11 не входит.' },
          { type: 'output', q: 'Что выведет программа? (сколько чисел кратных 7 от 1 до 30)',
            code: 'k = 0\nfor i in range(1, 31):\n    if i % 7 == 0:\n        k = k + 1\nprint(k)',
            answer: '4',
            explain: 'Кратные 7: 7,14,21,28 — четыре числа.' },
        ],
      },
    ],
  },

  // ── Юнит 8 ────────────────────────────────
  {
    id: 'oge_str',
    level: 'ОГЭ',
    icon: '🔤',
    color: '#a78bfa',
    title: 'Строки',
    desc: 'Длина, символы, перебор',
    lessons: [
      {
        id: 'oge_str_1',
        title: 'Работа со строками',
        xp: 10,
        questions: [
          { type: 'output', q: 'Что выведет программа?',
            code: 's = "Привет"\nprint(len(s))',
            answer: '6',
            explain: 'len() — длина строки. В "Привет" 6 букв.' },
          { type: 'output', q: 'Что выведет программа?',
            code: 's = "кот"\nprint(s[0])',
            answer: 'к',
            explain: 'Индексация с нуля: s[0] — первый символ "к".' },
          { type: 'output', q: 'Что выведет программа?',
            code: 's = "кот"\nprint(s[-1])',
            answer: 'т',
            explain: 'Отрицательный индекс -1 — последний символ "т".' },
          { type: 'output', q: 'Что выведет программа?',
            code: 'for c in "abc":\n    print(c)',
            answer: 'a\nb\nc',
            explain: 'Цикл for перебирает строку по буквам.' },
          { type: 'output', q: 'Что выведет программа?',
            code: 's = "ба" * 3\nprint(s)',
            answer: 'бабаба',
            explain: 'Строка * число повторяет её: "ба"*3 = "бабаба".' },
        ],
      },
    ],
  },
];
