// practice2.js — вторая волна практики. Новые вопросы экзаменационного уровня.
// Мержится в CURRICULUM по unitId.

export const EXTRA_LESSONS_2 = {
  // ── ОГЭ ──
  oge_print: [
    {
      id: 'oge_print_p2', title: 'Практика: вывод 2', xp: 12,
      questions: [
        { type: 'output', q: 'Что выведет программа?', code: 'print(5 * 2 + 1)', answer: '11',
          explain: 'Сначала 5*2=10, потом +1 = 11.' },
        { type: 'output', q: 'Что выведет программа?', code: 'print(1, 2, 3, 4)', answer: '1 2 3 4',
          explain: 'Запятые вставляют пробелы: 1 2 3 4.' },
        { type: 'output', q: 'Что выведет программа?', code: 'print("=" * 5)', answer: '=====',
          explain: 'Символ повторяется 5 раз.' },
        { type: 'output', q: 'Что выведет программа?', code: 'print(10 - 2 * 3)', answer: '4',
          explain: 'Умножение раньше: 2*3=6, потом 10-6=4.' },
        { type: 'output', q: 'Что выведет программа?', code: 'print("abc" + "123")', answer: 'abc123',
          explain: 'Склейка строк.' },
        { type: 'mcq', q: 'Что выведет print((2 + 3) * 2)?', code: 'print((2 + 3) * 2)',
          options: ['10', '8', '7', '12'], answer: 0,
          explain: 'Скобки первыми: (2+3)=5, потом 5*2=10.' },
        { type: 'output', q: 'Что выведет программа?', code: 'print(100 - 50 - 25)', answer: '25',
          explain: 'Слева направо: 100-50=50, 50-25=25.' },
        { type: 'output', q: 'Что выведет программа?', code: 'print("да " * 2)', answer: 'да да ',
          explain: '"да " (с пробелом) повторяется 2 раза.' },
        { type: 'bug', q: 'Что не так?', code: 'print(5 + )',
          options: ['После + не хватает второго числа', 'Нет кавычек', 'Лишняя скобка', 'Всё верно'], answer: 0,
          explain: 'Оператор + требует второе значение справа.' },
        { type: 'assemble', q: 'Собери: вывести результат 3 + 4 и слово "готово"',
          lines: ['print(3 + 4)', 'print("готово")'],
          explain: 'Сначала число, потом слово.' },
      ],
    },
  ],

  oge_vars: [
    {
      id: 'oge_vars_p2', title: 'Практика: переменные 2', xp: 12,
      questions: [
        { type: 'output', q: 'Что выведет программа?', code: 'a = 2\nb = 3\nc = a * b\nprint(c)', answer: '6',
          explain: 'c = 2 * 3 = 6.' },
        { type: 'output', q: 'Что выведет программа?', code: 'x = 100\nx = x - 30\nx = x - 20\nprint(x)', answer: '50',
          explain: '100 - 30 = 70, 70 - 20 = 50.' },
        { type: 'output', q: 'Что выведет программа?', code: 'a = 5\nb = a\nb = b + 10\nprint(a, b)', answer: '5 15',
          explain: 'a остался 5, b стал 15. Числа копируются по значению.' },
        { type: 'output', q: 'Что выведет программа?', code: 'x = "3"\ny = "4"\nprint(x + y)', answer: '34',
          explain: 'Строки склеиваются: "3"+"4"="34".' },
        { type: 'output', q: 'Что выведет программа?', code: 'n = 10\nn += 5\nprint(n)', answer: '15',
          explain: 'n += 5 то же, что n = n + 5. Стало 15.' },
        { type: 'output', q: 'Что выведет программа?', code: 'n = 20\nn -= 8\nprint(n)', answer: '12',
          explain: 'n -= 8 уменьшает на 8: 20-8=12.' },
        { type: 'output', q: 'Что выведет программа?', code: 'n = 3\nn *= 4\nprint(n)', answer: '12',
          explain: 'n *= 4 умножает: 3*4=12.' },
        { type: 'mcq', q: 'Что делает запись x += 1?',
          options: ['Увеличивает x на 1', 'Присваивает 1', 'Сравнивает', 'Ошибка'], answer: 0,
          explain: 'x += 1 то же, что x = x + 1.' },
        { type: 'bug', q: 'Что не так?', code: 'print(x)\nx = 5',
          options: ['Используем x до создания', 'Нет кавычек', 'x нельзя выводить', 'Всё верно'], answer: 0,
          explain: 'Переменную сначала создают, потом используют. Здесь порядок перепутан.' },
        { type: 'assemble', q: 'Собери: удвоить число 7 через переменную',
          lines: ['x = 7', 'x = x * 2', 'print(x)'],
          explain: 'Создать, удвоить, вывести.' },
      ],
    },
  ],

  oge_input: [
    {
      id: 'oge_input_p2', title: 'Практика: ввод 2', xp: 12,
      questions: [
        { type: 'mcq', q: 'Ввели 6. Что выведет код?', code: 'x = int(input())\nprint(x * x)',
          options: ['36', '66', '12', 'ошибка'], answer: 0,
          explain: 'x=6, 6*6=36.' },
        { type: 'mcq', q: 'Ввели 8. Что выведет код?', code: 'x = int(input())\nprint(x % 2)',
          options: ['0', '4', '8', '1'], answer: 0,
          explain: '8 чётное, остаток от деления на 2 равен 0.' },
        { type: 'mcq', q: 'Ввели 2 и 3. Что выведет код?', code: 'a = int(input())\nb = int(input())\nprint(a ** b)',
          options: ['8', '6', '5', '23'], answer: 0,
          explain: '2 в степени 3 = 8.' },
        { type: 'mcq', q: 'Почему код упадёт с ошибкой, если ввести "abc"?', code: 'x = int(input())',
          options: ['int не может превратить "abc" в число', 'input сломан', 'Нужны кавычки', 'Не упадёт'], answer: 0,
          explain: 'int() ждёт строку из цифр. "abc" превратить в число нельзя.' },
        { type: 'mcq', q: 'Ввели 5. Что выведет код?', code: 'x = int(input())\nprint(x + 1, x - 1)',
          options: ['6 4', '5 5', '4 6', '51'], answer: 0,
          explain: 'x+1=6, x-1=4, через запятую с пробелом.' },
        { type: 'bug', q: 'Ввели 5. Почему выведет 55, а не 10?', code: 'x = input()\nprint(x + x)',
          options: ['x — строка, "5"+"5"="55"', 'Ошибка', 'Выведет 10', 'input сломан'], answer: 0,
          explain: 'Без int() input даёт строку. Нужно int(input()).' },
        { type: 'assemble', q: 'Собери: считать число и вывести его +100',
          lines: ['x = int(input())', 'print(x + 100)'],
          explain: 'Считать как int, прибавить 100.' },
        { type: 'assemble', q: 'Собери: считать сторону квадрата и вывести площадь',
          lines: ['a = int(input())', 'print(a * a)'],
          explain: 'Площадь квадрата — сторона в квадрате.' },
      ],
    },
  ],

  oge_math: [
    {
      id: 'oge_math_p2', title: 'Практика: арифметика 2', xp: 12,
      questions: [
        { type: 'output', q: 'Что выведет программа?', code: 'print(25 % 7)', answer: '4',
          explain: '25 = 7*3 + 4. Остаток 4.' },
        { type: 'output', q: 'Что выведет программа?', code: 'print(25 // 7)', answer: '3',
          explain: '25 нацело на 7 — это 3.' },
        { type: 'output', q: 'Что выведет программа? (сумма цифр через остатки)', code: 'n = 48\nprint(n // 10 + n % 10)', answer: '12',
          explain: 'n//10=4, n%10=8, сумма 4+8=12.' },
        { type: 'output', q: 'Что выведет программа?', code: 'print(2 ** 8)', answer: '256',
          explain: '2 в 8-й степени = 256.' },
        { type: 'output', q: 'Что выведет программа?', code: 'print(9 // 2, 9 % 2)', answer: '4 1',
          explain: '9//2=4, 9%2=1.' },
        { type: 'mcq', q: 'Как получить первую цифру двузначного числа n?',
          options: ['n // 10', 'n % 10', 'n / 10', 'n * 10'], answer: 0,
          explain: 'n // 10 отбрасывает единицы, оставляя десятки.' },
        { type: 'output', q: 'Что выведет программа?', code: 'print(100 % 10)', answer: '0',
          explain: '100 делится на 10 нацело, остаток 0.' },
        { type: 'output', q: 'Что выведет программа?', code: 'print(1 + 2 ** 3)', answer: '9',
          explain: 'Степень раньше: 2**3=8, потом 1+8=9.' },
        { type: 'bug', q: 'Как проверить, что n делится на 3?',
          options: ['n % 3 == 0', 'n // 3 == 0', 'n / 3 == 0', 'n ** 3 == 0'], answer: 0,
          explain: 'Делимость — остаток 0: n % 3 == 0.' },
        { type: 'output', q: 'Что выведет программа?', code: 'print(15 // 4 + 15 % 4)', answer: '6',
          explain: '15//4=3, 15%4=3, сумма 6.' },
      ],
    },
  ],

  oge_if: [
    {
      id: 'oge_if_p2', title: 'Практика: условия 2', xp: 12,
      questions: [
        { type: 'output', q: 'Что выведет программа?', code: 'x = 100\nif x >= 100:\n    print("сотня")\nelse:\n    print("мало")', answer: 'сотня',
          explain: '100 >= 100 истинно.' },
        { type: 'output', q: 'Что выведет программа?', code: 'a = 7\nif a < 5:\n    print("A")\nelif a < 10:\n    print("B")\nelse:\n    print("C")', answer: 'B',
          explain: '7 не меньше 5, но меньше 10 → ветка B.' },
        { type: 'output', q: 'Что выведет программа? (оценка по баллу)', code: 'b = 85\nif b >= 90:\n    print("5")\nelif b >= 75:\n    print("4")\nelse:\n    print("3")', answer: '4',
          explain: '85 не дотянул до 90, но >= 75 → оценка 4.' },
        { type: 'output', q: 'Что выведет программа?', code: 'x = 4\ny = 9\nif x > y or y > 5:\n    print("да")\nelse:\n    print("нет")', answer: 'да',
          explain: 'or: x>y ложно, но y>5 (9>5) истинно → да.' },
        { type: 'output', q: 'Что выведет программа?', code: 'x = 6\nif x > 0 and x % 2 == 0:\n    print("положительное чётное")', answer: 'положительное чётное',
          explain: '6 больше 0 И чётное — оба условия истинны.' },
        { type: 'output', q: 'Что выведет программа?', code: 'a = 5\nif not a > 10:\n    print("не больше 10")', answer: 'не больше 10',
          explain: 'a>10 ложно, not делает истинным.' },
        { type: 'mcq', q: 'Когда сработает ветка elif?',
          options: ['Если if ложно, а elif истинно', 'Всегда', 'Если if истинно', 'Никогда'], answer: 0,
          explain: 'elif проверяется только если предыдущее условие ложно.' },
        { type: 'bug', q: 'Что не так?', code: 'x = 5\nif x > 3\n    print("да")',
          options: ['Нет двоеточия после условия', 'Нужно ==', 'Нет else', 'Всё верно'], answer: 0,
          explain: 'После условия if нужно двоеточие.' },
        { type: 'assemble', q: 'Собери: вывести знак числа (плюс/ноль/минус)',
          lines: ['x = -3', 'if x > 0:', '    print("плюс")', 'elif x == 0:', '    print("ноль")', 'else:', '    print("минус")'],
          explain: 'Три ветки: if, elif, else.' },
      ],
    },
  ],

  oge_while: [
    {
      id: 'oge_while_p2', title: 'Практика: while 2', xp: 12,
      questions: [
        { type: 'output', q: 'Что выведет программа?', code: 'i = 5\nwhile i > 0:\n    print(i)\n    i = i - 1', answer: '5\n4\n3\n2\n1',
          explain: 'От 5 вниз до 1, пока i > 0.' },
        { type: 'output', q: 'Что выведет программа? (произведение 1..4)', code: 'p = 1\ni = 1\nwhile i <= 4:\n    p = p * i\n    i = i + 1\nprint(p)', answer: '24',
          explain: '1*2*3*4 = 24.' },
        { type: 'output', q: 'Что выведет программа? (кол-во цифр 3050)', code: 'n = 3050\nk = 0\nwhile n > 0:\n    k = k + 1\n    n = n // 10\nprint(k)', answer: '4',
          explain: 'В 3050 четыре цифры.' },
        { type: 'output', q: 'Что выведет программа?', code: 'n = 16\nk = 0\nwhile n > 1:\n    n = n // 2\n    k = k + 1\nprint(k)', answer: '4',
          explain: '16→8→4→2→1: четыре деления.' },
        { type: 'output', q: 'Что выведет программа? (сумма чётных до 10)', code: 's = 0\ni = 2\nwhile i <= 10:\n    s = s + i\n    i = i + 2\nprint(s)', answer: '30',
          explain: '2+4+6+8+10 = 30.' },
        { type: 'output', q: 'Что выведет программа? (макс цифра 5273)', code: 'n = 5273\nm = 0\nwhile n > 0:\n    d = n % 10\n    if d > m:\n        m = d\n    n = n // 10\nprint(m)', answer: '7',
          explain: 'Цифры 5,2,7,3 — максимальная 7.' },
        { type: 'bug', q: 'Почему цикл зациклится навсегда?', code: 'i = 1\nwhile i <= 5:\n    print(i)',
          options: ['Не меняется i внутри цикла', 'Нет условия', 'Нет print', 'Не зациклится'], answer: 0,
          explain: 'Без i = i + 1 условие всегда истинно — бесконечный цикл.' },
        { type: 'assemble', q: 'Собери: вывести числа от 3 до 1 (вниз)',
          lines: ['i = 3', 'while i >= 1:', '    print(i)', '    i = i - 1'],
          explain: 'Счётчик вниз с i = i - 1.' },
      ],
    },
  ],

  oge_for: [
    {
      id: 'oge_for_p2', title: 'Практика: for 2', xp: 12,
      questions: [
        { type: 'output', q: 'Что выведет программа?', code: 'for i in range(2, 6):\n    print(i)', answer: '2\n3\n4\n5',
          explain: 'range(2,6) = 2,3,4,5.' },
        { type: 'output', q: 'Что выведет программа? (сумма кратных 5 до 20)', code: 's = 0\nfor i in range(5, 21, 5):\n    s = s + i\nprint(s)', answer: '50',
          explain: '5+10+15+20 = 50.' },
        { type: 'output', q: 'Что выведет программа?', code: 'for i in range(3):\n    print(i * 2)', answer: '0\n2\n4',
          explain: 'i=0,1,2 → печатаем 0,2,4.' },
        { type: 'output', q: 'Что выведет программа? (факториал 5)', code: 'f = 1\nfor i in range(1, 6):\n    f = f * i\nprint(f)', answer: '120',
          explain: '1*2*3*4*5 = 120.' },
        { type: 'output', q: 'Что выведет программа? (сколько нечётных до 10)', code: 'k = 0\nfor i in range(1, 11):\n    if i % 2 == 1:\n        k = k + 1\nprint(k)', answer: '5',
          explain: 'Нечётные: 1,3,5,7,9 — пять чисел.' },
        { type: 'output', q: 'Что выведет программа?', code: 'for i in range(4, 0, -1):\n    print(i)', answer: '4\n3\n2\n1',
          explain: 'От 4 вниз до 1 с шагом -1.' },
        { type: 'output', q: 'Что выведет программа? (сумма квадратов 1..3)', code: 's = 0\nfor i in range(1, 4):\n    s = s + i * i\nprint(s)', answer: '14',
          explain: '1+4+9 = 14.' },
        { type: 'mcq', q: 'Сколько чисел даёт range(2, 20, 3)?',
          options: ['6', '7', '5', '18'], answer: 0,
          explain: '2,5,8,11,14,17 — шесть чисел.' },
        { type: 'bug', q: 'Почему range(1, 5) даёт 4 числа, а не 5?',
          options: ['Правая граница 5 не входит', 'Ошибка', 'Всегда 4', 'Начинает с 1'], answer: 0,
          explain: 'range(1,5) = 1,2,3,4. Число 5 не включается.' },
        { type: 'assemble', q: 'Собери: сумма чисел от 1 до 10',
          lines: ['s = 0', 'for i in range(1, 11):', '    s = s + i', 'print(s)'],
          explain: 'Накопитель, цикл до 11 (10 включительно), вывод.' },
      ],
    },
  ],

  oge_str: [
    {
      id: 'oge_str_p2', title: 'Практика: строки 2', xp: 12,
      questions: [
        { type: 'output', q: 'Что выведет программа?', code: 's = "программа"\nprint(len(s))', answer: '9',
          explain: 'В слове "программа" 9 букв.' },
        { type: 'output', q: 'Что выведет программа?', code: 's = "Python"\nprint(s[0] + s[-1])', answer: 'Pn',
          explain: 'Первый символ P + последний n = "Pn".' },
        { type: 'output', q: 'Что выведет программа? (кол-во "о")', code: 'k = 0\nfor c in "молоко":\n    if c == "о":\n        k = k + 1\nprint(k)', answer: '3',
          explain: 'В "молоко" буква "о" встречается 3 раза.' },
        { type: 'output', q: 'Что выведет программа?', code: 's = "ab"\nprint(s * 3)', answer: 'ababab',
          explain: '"ab" повторяется 3 раза.' },
        { type: 'output', q: 'Что выведет программа? (склейка в цикле)', code: 'r = ""\nfor c in "abc":\n    r = c + r\nprint(r)', answer: 'cba',
          explain: 'Каждая буква добавляется В НАЧАЛО — получается переворот: cba.' },
        { type: 'output', q: 'Что выведет программа?', code: 's = "hello"\nprint(s[1:3])', answer: 'el',
          explain: 'Срез с 1 по 2: символы e, l.' },
        { type: 'output', q: 'Что выведет программа? (длина каждого слова)', code: 'for w in ["кот", "пёс", "конь"]:\n    print(len(w))', answer: '3\n3\n4',
          explain: 'Длины: кот=3, пёс=3, конь=4.' },
        { type: 'mcq', q: 'Как обратиться к последнему символу строки s?',
          options: ['s[-1]', 's[len(s)]', 's[end]', 's.last'], answer: 0,
          explain: 's[-1] — последний символ. s[len(s)] выйдет за границы.' },
        { type: 'bug', q: 'Что не так?', code: 's = "кот"\nprint(s[3])',
          options: ['Нет символа с индексом 3 (только 0,1,2)', 'Строка пустая', 'Нужны кавычки', 'Всё верно'], answer: 0,
          explain: 'В строке из 3 букв индексы 0,1,2. s[3] — ошибка.' },
        { type: 'assemble', q: 'Собери: вывести первую и последнюю букву слова',
          lines: ['s = "школа"', 'print(s[0])', 'print(s[-1])'],
          explain: 'Первый символ [0], последний [-1].' },
      ],
    },
  ],

  // ── ЕГЭ ──
  ege_lists: [
    {
      id: 'ege_lists_p2', title: 'Практика: списки 2', xp: 15,
      questions: [
        { type: 'output', q: 'Что выведет программа?', code: 'a = [3, 1, 4, 1, 5]\nprint(sum(a))', answer: '14',
          explain: '3+1+4+1+5 = 14.' },
        { type: 'output', q: 'Что выведет программа? (среднее)', code: 'a = [10, 20, 30]\nprint(sum(a) // len(a))', answer: '20',
          explain: 'Сумма 60, делим на 3 = 20.' },
        { type: 'output', q: 'Что выведет программа? (кол-во нулей)', code: 'a = [0, 5, 0, 3, 0]\nk = 0\nfor x in a:\n    if x == 0:\n        k = k + 1\nprint(k)', answer: '3',
          explain: 'Нулей в списке — 3.' },
        { type: 'output', q: 'Что выведет программа?', code: 'a = [1, 2, 3, 4, 5]\nprint(a[-1] + a[-2])', answer: '9',
          explain: 'Последний 5 + предпоследний 4 = 9.' },
        { type: 'output', q: 'Что выведет программа? (макс - мин)', code: 'a = [7, 3, 9, 2, 8]\nprint(max(a) - min(a))', answer: '7',
          explain: 'max=9, min=2, разность 7.' },
        { type: 'output', q: 'Что выведет программа? (сумма нечётных)', code: 'a = [1, 2, 3, 4, 5, 6]\ns = 0\nfor x in a:\n    if x % 2 == 1:\n        s = s + x\nprint(s)', answer: '9',
          explain: 'Нечётные 1+3+5 = 9.' },
        { type: 'output', q: 'Что выведет программа?', code: 'a = [4, 8, 15, 16, 23]\nprint(a[1:4])', answer: '[8, 15, 16]',
          explain: 'Срез с 1 по 3: 8, 15, 16.' },
        { type: 'output', q: 'Что выведет программа? (кол-во элементов больше среднего... нет — больше 3)', code: 'a = [1, 5, 2, 8, 3]\nk = 0\nfor x in a:\n    if x > 3:\n        k = k + 1\nprint(k)', answer: '2',
          explain: 'Больше 3: 5 и 8 — два элемента.' },
        { type: 'bug', q: 'Как получить количество элементов списка a?',
          options: ['len(a)', 'a.count()', 'size(a)', 'a.length'], answer: 0,
          explain: 'len(a) возвращает длину списка.' },
        { type: 'assemble', q: 'Собери: посчитать сумму элементов списка через цикл',
          lines: ['a = [10, 20, 30]', 's = 0', 'for x in a:', '    s = s + x', 'print(s)'],
          explain: 'Накопитель, перебор, вывод.' },
      ],
    },
  ],

  ege_nested: [
    {
      id: 'ege_nested_p2', title: 'Практика: вложенные 2', xp: 15,
      questions: [
        { type: 'output', q: 'Что выведет программа?', code: 'for i in range(1, 4):\n    for j in range(i):\n        print(i, end=" ")\n    print()', answer: '1 \n2 2 \n3 3 3 ',
          explain: 'В строке i выводится i раз число i.' },
        { type: 'output', q: 'Сколько раз выполнится тело?', code: 'k = 0\nfor i in range(5):\n    for j in range(3):\n        k += 1\nprint(k)', answer: '15',
          explain: '5 × 3 = 15.' },
        { type: 'output', q: 'Что выведет программа? (таблица умножения 2x2)', code: 'for i in range(1, 3):\n    for j in range(1, 3):\n        print(i * j, end=" ")\n    print()', answer: '1 2 \n2 4 ',
          explain: 'Произведения: (1·1 1·2)(2·1 2·2).' },
        { type: 'output', q: 'Что выведет программа?', code: 's = 0\nfor i in range(3):\n    for j in range(3):\n        if i == j:\n            s += 1\nprint(s)', answer: '3',
          explain: 'i==j когда (0,0),(1,1),(2,2) — три раза.' },
        { type: 'mcq', q: 'Внешний цикл range(4), внутренний range(5). Сколько итераций тела?',
          options: ['20', '9', '4', '5'], answer: 0,
          explain: '4 × 5 = 20.' },
        { type: 'assemble', q: 'Собери: вывести все пары (i, j) для i,j из range(2)',
          lines: ['for i in range(2):', '    for j in range(2):', '        print(i, j)'],
          explain: 'Внешний и внутренний циклы, печать пары.' },
      ],
    },
  ],

  ege_func: [
    {
      id: 'ege_func_p2', title: 'Практика: функции 2', xp: 15,
      questions: [
        { type: 'output', q: 'Что выведет программа?', code: 'def f(x):\n    return x + 100\nprint(f(1) + f(2))', answer: '203',
          explain: 'f(1)=101, f(2)=102, сумма 203.' },
        { type: 'output', q: 'Что выведет программа?', code: 'def kub(x):\n    return x ** 3\nprint(kub(3))', answer: '27',
          explain: '3 в кубе = 27.' },
        { type: 'output', q: 'Что выведет программа?', code: 'def sr(a, b):\n    return (a + b) // 2\nprint(sr(10, 20))', answer: '15',
          explain: 'Среднее: (10+20)//2 = 15.' },
        { type: 'output', q: 'Что выведет программа?', code: 'def f(n):\n    if n > 0:\n        return "+"\n    return "-"\nprint(f(-5))', answer: '-',
          explain: '-5 не больше 0 → возвращается "-".' },
        { type: 'output', q: 'Что выведет программа? (функция без return)', code: 'def f(x):\n    y = x * 2\nprint(f(3))', answer: 'None',
          explain: 'Без return функция возвращает None.' },
        { type: 'output', q: 'Что выведет программа? (вызов в цикле)', code: 'def sq(x):\n    return x * x\nfor i in range(1, 4):\n    print(sq(i))', answer: '1\n4\n9',
          explain: 'sq(1)=1, sq(2)=4, sq(3)=9.' },
        { type: 'mcq', q: 'Что вернёт функция, если в ней нет return?',
          options: ['None', '0', 'Пустую строку', 'Ошибку'], answer: 0,
          explain: 'Без return функция возвращает None.' },
        { type: 'bug', q: 'Почему выведет None?', code: 'def f(x):\n    print(x * 2)\nresult = f(5)\nprint(result)',
          options: ['f печатает, но не возвращает — result = None', 'Ошибка', 'result = 10', 'Всё верно'], answer: 0,
          explain: 'Внутри print, но нет return. Функция возвращает None.' },
        { type: 'assemble', q: 'Собери функцию, возвращающую сумму цифр... нет, площадь прямоугольника',
          lines: ['def area(a, b):', '    return a * b', 'print(area(3, 4))'],
          explain: 'Площадь = произведение сторон.' },
      ],
    },
  ],

  ege_str2: [
    {
      id: 'ege_str2_p2', title: 'Практика: строки ЕГЭ 2', xp: 15,
      questions: [
        { type: 'output', q: 'Что выведет программа?', code: 's = "abcdef"\nprint(s[1:5:2])', answer: 'bd',
          explain: 'Срез с 1 по 4 с шагом 2: индексы 1,3 → b, d.' },
        { type: 'output', q: 'Что выведет программа?', code: 's = "12345"\nprint(s[::-1])', answer: '54321',
          explain: 'Переворот строки.' },
        { type: 'output', q: 'Что выведет программа?', code: 's = "Hello World"\nprint(s.count("o"))', answer: '2',
          explain: 'Буква "o" встречается 2 раза.' },
        { type: 'output', q: 'Что выведет программа?', code: 'print("a,b,c,d".split(","))', answer: "['a', 'b', 'c', 'd']",
          explain: 'split(",") разбивает по запятой.' },
        { type: 'output', q: 'Что выведет программа?', code: 'print("-".join(["1", "2", "3"]))', answer: '1-2-3',
          explain: 'join склеивает через дефис.' },
        { type: 'output', q: 'Что выведет программа?', code: 's = "Привет"\nprint(s.upper())', answer: 'ПРИВЕТ',
          explain: 'upper() — заглавные буквы.' },
        { type: 'output', q: 'Что выведет программа?', code: 's = "abcabc"\nprint(s.replace("a", "X"))', answer: 'XbcXbc',
          explain: 'replace заменяет все "a" на "X".' },
        { type: 'output', q: 'Что выведет программа?', code: 's = "hello"\nprint(s.find("l"))', answer: '2',
          explain: 'find возвращает индекс первого "l" — это 2.' },
        { type: 'bug', q: 'Что вернёт "abc".find("z")?', code: 'print("abc".find("z"))',
          options: ['-1 (не найдено)', '0', 'ошибку', '3'], answer: 0,
          explain: 'Если подстрока не найдена, find возвращает -1.' },
        { type: 'assemble', q: 'Собери: перевернуть строку и вывести',
          lines: ['s = "Python"', 'print(s[::-1])'],
          explain: 'Срез [::-1] переворачивает.' },
      ],
    },
  ],

  ege_dict: [
    {
      id: 'ege_dict_p2', title: 'Практика: словари 2', xp: 15,
      questions: [
        { type: 'output', q: 'Что выведет программа?', code: 'd = {"a": 10, "b": 20, "c": 30}\nprint(d["a"] + d["c"])', answer: '40',
          explain: '10 + 30 = 40.' },
        { type: 'output', q: 'Что выведет программа?', code: 'd = {}\nd["x"] = 1\nd["y"] = 2\nd["x"] = 5\nprint(d["x"])', answer: '5',
          explain: 'Ключ "x" перезаписан на 5.' },
        { type: 'output', q: 'Что выведет программа? (сумма значений)', code: 'd = {"a": 1, "b": 2, "c": 3}\ns = 0\nfor k in d:\n    s = s + d[k]\nprint(s)', answer: '6',
          explain: 'Перебор ключей, сумма значений 1+2+3=6.' },
        { type: 'output', q: 'Что выведет программа? (частоты)', code: 'd = {}\nfor c in "abracadabra":\n    d[c] = d.get(c, 0) + 1\nprint(d["a"])', answer: '5',
          explain: 'В "abracadabra" буква "a" — 5 раз.' },
        { type: 'output', q: 'Что выведет программа? (уникальные)', code: 'a = [1, 2, 2, 3, 3, 3, 4]\nprint(len(set(a)))', answer: '4',
          explain: 'Уникальные: 1,2,3,4 — четыре.' },
        { type: 'output', q: 'Что выведет программа?', code: 's = set([1, 2, 3])\nprint(2 in s)', answer: 'True',
          explain: '2 есть в множестве → True.' },
        { type: 'mcq', q: 'Что делает d.get("x", 0), если ключа "x" нет?',
          options: ['Возвращает 0', 'Ошибку', 'Создаёт ключ', 'Возвращает None'], answer: 0,
          explain: 'get с двумя аргументами возвращает второй, если ключа нет.' },
        { type: 'bug', q: 'Что будет при обращении к несуществующему ключу?', code: 'd = {"a": 1}\nprint(d["b"])',
          options: ['Ошибка KeyError', 'Выведет 0', 'Выведет None', 'Создаст ключ'], answer: 0,
          explain: 'Прямое обращение d["b"] к отсутствующему ключу — ошибка. Безопаснее d.get("b", 0).' },
        { type: 'assemble', q: 'Собери: посчитать количество уникальных чисел',
          lines: ['a = [1, 2, 2, 3]', 's = set(a)', 'print(len(s))'],
          explain: 'set убирает дубликаты, len считает.' },
      ],
    },
  ],

  ege_lib: [
    {
      id: 'ege_lib_p2', title: 'Практика: библиотеки 2', xp: 15,
      questions: [
        { type: 'output', q: 'Что выведет программа?', code: 'import math\nprint(math.sqrt(144))', answer: '12.0',
          explain: 'Корень из 144 = 12.0.' },
        { type: 'output', q: 'Что выведет программа?', code: 'import math\nprint(math.floor(7.9))', answer: '7',
          explain: 'floor округляет вниз до 7.' },
        { type: 'output', q: 'Что выведет программа?', code: 'import math\nprint(math.ceil(7.1))', answer: '8',
          explain: 'ceil округляет вверх до 8.' },
        { type: 'output', q: 'Что выведет программа?', code: 'print(abs(-15))', answer: '15',
          explain: 'Модуль -15 равен 15.' },
        { type: 'output', q: 'Что выведет программа?', code: 'print(round(2.5), round(3.14))', answer: '2 3',
          explain: 'round(2.5)=2 (банковское округление), round(3.14)=3.' },
        { type: 'output', q: 'Что выведет программа?', code: 'import math\nprint(math.factorial(3))', answer: '6',
          explain: '3! = 1*2*3 = 6.' },
        { type: 'output', q: 'Что выведет программа?', code: 'print(max(3, 7, 2))', answer: '7',
          explain: 'max из нескольких аргументов = 7.' },
        { type: 'output', q: 'Что выведет программа?', code: 'print(min(5, 1, 9, 3))', answer: '1',
          explain: 'min = 1.' },
        { type: 'mcq', q: 'Что нужно написать перед использованием math.sqrt?',
          options: ['import math', 'use math', 'include math', 'ничего'], answer: 0,
          explain: 'Модуль подключается через import math.' },
        { type: 'assemble', q: 'Собери: вывести корень из 81',
          lines: ['import math', 'print(math.sqrt(81))'],
          explain: 'Подключить math, вызвать sqrt.' },
      ],
    },
  ],

  ege_algo: [
    {
      id: 'ege_algo_p2', title: 'Практика: задачи ЕГЭ 2', xp: 20,
      questions: [
        { type: 'output', q: 'Что выведет программа? (сумма цифр 9999)', code: 'n = 9999\ns = 0\nwhile n > 0:\n    s += n % 10\n    n //= 10\nprint(s)', answer: '36',
          explain: '9+9+9+9 = 36.' },
        { type: 'output', q: 'Что выведет программа? (сколько делится на 4 от 1 до 20)', code: 'k = 0\nfor i in range(1, 21):\n    if i % 4 == 0:\n        k += 1\nprint(k)', answer: '5',
          explain: 'Кратные 4: 4,8,12,16,20 — пять.' },
        { type: 'output', q: 'Что выведет программа? (наибольшая цифра 4826)', code: 'n = 4826\nm = 0\nwhile n > 0:\n    d = n % 10\n    if d > m:\n        m = d\n    n //= 10\nprint(m)', answer: '8',
          explain: 'Цифры 4,8,2,6 — максимум 8.' },
        { type: 'output', q: 'Что выведет программа? (кол-во делителей 16)', code: 'n = 16\nk = 0\nfor d in range(1, n + 1):\n    if n % d == 0:\n        k += 1\nprint(k)', answer: '5',
          explain: 'Делители 16: 1,2,4,8,16 — пять.' },
        { type: 'output', q: 'Что выведет программа? (сумма элементов больше 5)', code: 'a = [3, 7, 2, 9, 6, 1]\ns = 0\nfor x in a:\n    if x > 5:\n        s += x\nprint(s)', answer: '22',
          explain: 'Больше 5: 7+9+6 = 22.' },
        { type: 'output', q: 'Что выведет программа? (индекс максимума)', code: 'a = [3, 8, 5, 8, 2]\nmi = 0\nfor i in range(len(a)):\n    if a[i] > a[mi]:\n        mi = i\nprint(mi)', answer: '1',
          explain: 'Первый максимум 8 стоит на индексе 1.' },
        { type: 'output', q: 'Что выведет программа? (палиндром?)', code: 's = "abcba"\nprint(s == s[::-1])', answer: 'True',
          explain: '"abcba" читается одинаково в обе стороны — палиндром.' },
        { type: 'output', q: 'Что выведет программа? (среднее целое)', code: 'a = [4, 8, 6, 2]\nprint(sum(a) // len(a))', answer: '5',
          explain: 'Сумма 20, делим на 4 = 5.' },
        { type: 'assemble', q: 'Собери: посчитать сумму цифр числа n',
          lines: ['n = 123', 's = 0', 'while n > 0:', '    s += n % 10', '    n //= 10', 'print(s)'],
          explain: 'Отделяем цифры через %10 и //10, накапливаем.' },
      ],
    },
  ],
};
