// practice.js — дополнительные практические уроки к каждому юниту.
// Мержатся в CURRICULUM по unitId (см. curriculum/index.js).

export const EXTRA_LESSONS = {
  // ── ОГЭ ──
  oge_print: [
    {
      id: 'oge_print_p1', title: 'Практика: вывод', xp: 12,
      questions: [
        { type: 'output', q: 'Что выведет программа?', code: 'print(3 * 4)', answer: '12',
          explain: '3 умножить на 4 — это 12.' },
        { type: 'output', q: 'Что выведет программа?', code: 'print("5" * 3)', answer: '555',
          explain: 'Строка "5" повторяется 3 раза → "555".' },
        { type: 'mcq', q: 'Что выведет программа?', code: 'print(10 - 4 - 3)',
          options: ['3', '9', '11', '10'], answer: 0,
          explain: 'Слева направо: 10 - 4 = 6, потом 6 - 3 = 3.' },
        { type: 'output', q: 'Что выведет программа?', code: 'print("a", "b", "c")', answer: 'a b c',
          explain: 'Запятые вставляют пробелы между значениями.' },
        { type: 'output', q: 'Что выведет программа?', code: 'print(2 + 2 * 2)', answer: '6',
          explain: 'Сначала умножение: 2*2=4, потом 2+4=6.' },
        { type: 'output', q: 'Что выведет программа?', code: 'print("да" + "нет")', answer: 'данет',
          explain: 'Плюс склеивает строки без пробела.' },
        { type: 'mcq', q: 'Сколько строк выведет этот код?', code: 'print("1")\nprint("2")\nprint("3")',
          options: ['1', '2', '3', '6'], answer: 2,
          explain: 'Три команды print — три строки.' },
        { type: 'output', q: 'Что выведет программа?', code: 'print(100 // 10)', answer: '10',
          explain: '100 разделить нацело на 10 — это 10.' },
        { type: 'mcq', q: 'Как вывести результат 2 + 3 как число?',
          options: ['print(2 + 3)', 'print("2 + 3")', 'print(2, +, 3)', '2 + 3'], answer: 0,
          explain: 'Без кавычек Python посчитает: 2 + 3 = 5. С кавычками вывелось бы «2 + 3».' },
      ],
    },
  ],

  oge_vars: [
    {
      id: 'oge_vars_p1', title: 'Практика: переменные', xp: 12,
      questions: [
        { type: 'output', q: 'Что выведет программа?', code: 'a = 4\nb = a + 2\nprint(b)', answer: '6',
          explain: 'b = 4 + 2 = 6.' },
        { type: 'output', q: 'Что выведет программа?', code: 'x = 10\ny = x\nx = 20\nprint(y)', answer: '10',
          explain: 'y получил значение 10 в момент присваивания. Изменение x его не меняет.' },
        { type: 'output', q: 'Что выведет программа?', code: 'a = 5\nb = 3\na = b\nprint(a)', answer: '3',
          explain: 'a = b означает: положить в a значение b (3).' },
        { type: 'output', q: 'Что выведет программа? (обмен значений)', code: 'a = 1\nb = 2\na, b = b, a\nprint(a, b)', answer: '2 1',
          explain: 'a, b = b, a меняет значения местами.' },
        { type: 'mcq', q: 'Какое имя переменной допустимо?',
          options: ['1num', 'my num', 'my_num', 'my-num'], answer: 2,
          explain: 'Имя из букв, цифр и _. Пробелы и дефисы нельзя, начинать с цифры нельзя.' },
        { type: 'output', q: 'Что выведет программа?', code: 's = "мама"\nprint(s + " " + s)', answer: 'мама мама',
          explain: 'Склеиваем строку, пробел и снова строку.' },
        { type: 'output', q: 'Что выведет программа?', code: 'x = 7\nx = x + 1\nprint(x)', answer: '8',
          explain: 'x увеличивается на 1: было 7, стало 8.' },
        { type: 'output', q: 'Что выведет программа?', code: 'n = 5\nn = n * n\nprint(n)', answer: '25',
          explain: 'n умножается само на себя: 5*5 = 25.' },
      ],
    },
  ],

  oge_input: [
    {
      id: 'oge_input_p1', title: 'Практика: ввод', xp: 12,
      questions: [
        { type: 'mcq', q: 'Ввели 3 и 4. Что выведет код?', code: 'a = int(input())\nb = int(input())\nprint(a + b)',
          options: ['34', '7', '12', 'ошибка'], answer: 1,
          explain: 'Оба числа стали int, 3 + 4 = 7.' },
        { type: 'mcq', q: 'Ввели 3 и 4. Что выведет код?', code: 'a = input()\nb = input()\nprint(a + b)',
          options: ['34', '7', '12', 'ошибка'], answer: 0,
          explain: 'Без int это строки. "3" + "4" = "34".' },
        { type: 'mcq', q: 'Как считать вещественное число (с точкой)?',
          options: ['int(input())', 'float(input())', 'input()', 'str(input())'], answer: 1,
          explain: 'float() превращает строку в дробное число.' },
        { type: 'mcq', q: 'Ввели 10. Что выведет код?', code: 'x = int(input())\nprint(x * 2)',
          options: ['1010', '20', '102', 'ошибка'], answer: 1,
          explain: 'x — число 10, 10 * 2 = 20.' },
        { type: 'mcq', q: 'Что вернёт input() если ввели 42?',
          options: ['Число 42', 'Строку "42"', 'Дробь 42.0', 'Ошибку'], answer: 1,
          explain: 'input() всегда возвращает строку.' },
        { type: 'assemble', q: 'Собери: считать число и вывести его удвоенное значение',
          lines: ['x = int(input())', 'print(x * 2)'],
          explain: 'Считать как int, умножить на 2.' },
        { type: 'assemble', q: 'Собери: считать два числа и вывести их сумму',
          lines: ['a = int(input())', 'b = int(input())', 'print(a + b)'],
          explain: 'Два ввода, потом сумма.' },
      ],
    },
  ],

  oge_math: [
    {
      id: 'oge_math_p1', title: 'Практика: арифметика', xp: 12,
      questions: [
        { type: 'output', q: 'Что выведет программа?', code: 'print(20 % 6)', answer: '2',
          explain: '20 = 6*3 + 2. Остаток 2.' },
        { type: 'output', q: 'Что выведет программа?', code: 'print(20 // 6)', answer: '3',
          explain: '20 делить нацело на 6 — это 3.' },
        { type: 'output', q: 'Что выведет программа?', code: 'print(3 ** 3)', answer: '27',
          explain: '3 в кубе = 3*3*3 = 27.' },
        { type: 'mcq', q: 'Как проверить, что число делится на 5?',
          options: ['x / 5 == 0', 'x % 5 == 0', 'x // 5 == 0', 'x ** 5 == 0'], answer: 1,
          explain: 'Делится нацело = остаток 0: x % 5 == 0.' },
        { type: 'output', q: 'Что выведет программа? (последняя цифра числа)', code: 'n = 347\nprint(n % 10)', answer: '7',
          explain: 'Остаток от деления на 10 — последняя цифра.' },
        { type: 'output', q: 'Что выведет программа? (число без последней цифры)', code: 'n = 347\nprint(n // 10)', answer: '34',
          explain: 'Деление нацело на 10 убирает последнюю цифру.' },
        { type: 'output', q: 'Что выведет программа?', code: 'print(10 / 4)', answer: '2.5',
          explain: 'Обычное деление даёт дробь: 2.5.' },
        { type: 'output', q: 'Что выведет программа?', code: 'print(2 ** 5)', answer: '32',
          explain: '2 в 5-й степени = 32.' },
        { type: 'mcq', q: 'Чему равно 15 % 4?', code: 'print(15 % 4)',
          options: ['3', '4', '11', '1'], answer: 0,
          explain: '15 = 4*3 + 3. Остаток 3.' },
      ],
    },
  ],

  oge_if: [
    {
      id: 'oge_if_p1', title: 'Практика: условия', xp: 12,
      questions: [
        { type: 'output', q: 'Что выведет программа?', code: 'x = 5\nif x > 3:\n    print("A")\nif x > 10:\n    print("B")', answer: 'A',
          explain: 'Первое условие истинно (5>3), второе ложно (5>10 нет).' },
        { type: 'output', q: 'Что выведет программа?', code: 'a = 4\nif a % 2 == 0:\n    print("чёт")\nelse:\n    print("нечёт")', answer: 'чёт',
          explain: '4 делится на 2 — чётное.' },
        { type: 'output', q: 'Что выведет программа?', code: 'x = -5\nif x > 0:\n    print("плюс")\nelif x == 0:\n    print("ноль")\nelse:\n    print("минус")', answer: 'минус',
          explain: 'x меньше 0, срабатывает else.' },
        { type: 'output', q: 'Что выведет программа? (максимум)', code: 'a = 12\nb = 7\nif a > b:\n    print(a)\nelse:\n    print(b)', answer: '12',
          explain: 'Выводит большее число. 12 > 7.' },
        { type: 'mcq', q: 'Что означает условие 3 < x < 8?',
          options: ['x между 3 и 8', 'x равно 3 или 8', 'x больше 8', 'ошибка'], answer: 0,
          explain: 'В Python можно писать двойное сравнение: x больше 3 И меньше 8.' },
        { type: 'output', q: 'Что выведет программа?', code: 'x = 6\nif x > 0 and x < 10:\n    print("да")\nelse:\n    print("нет")', answer: 'да',
          explain: '6 больше 0 И меньше 10 — оба условия истинны.' },
        { type: 'output', q: 'Что выведет программа?', code: 'x = 15\nif x > 10 or x < 0:\n    print("да")\nelse:\n    print("нет")', answer: 'да',
          explain: 'or достаточно одного истинного: 15 > 10.' },
        { type: 'assemble', q: 'Собери: если x чётное — вывести "чёт"',
          lines: ['x = 8', 'if x % 2 == 0:', '    print("чёт")'],
          explain: 'Проверка чётности через остаток, тело с отступом.' },
      ],
    },
  ],

  oge_while: [
    {
      id: 'oge_while_p1', title: 'Практика: while', xp: 12,
      questions: [
        { type: 'output', q: 'Что выведет программа?', code: 'i = 0\nwhile i < 3:\n    print(i)\n    i = i + 1', answer: '0\n1\n2',
          explain: 'i идёт от 0, пока меньше 3: 0, 1, 2.' },
        { type: 'output', q: 'Что выведет программа? (сумма 1..5)', code: 's = 0\ni = 1\nwhile i <= 5:\n    s = s + i\n    i = i + 1\nprint(s)', answer: '15',
          explain: '1+2+3+4+5 = 15.' },
        { type: 'output', q: 'Что выведет программа?', code: 'n = 8\nwhile n > 1:\n    n = n // 2\nprint(n)', answer: '1',
          explain: '8→4→2→1, цикл останавливается когда n=1.' },
        { type: 'output', q: 'Сколько раз выполнится тело?', code: 'i = 10\nk = 0\nwhile i > 0:\n    i = i - 2\n    k = k + 1\nprint(k)', answer: '5',
          explain: 'i: 10→8→6→4→2→0, тело сработало 5 раз.' },
        { type: 'mcq', q: 'Когда цикл while станет бесконечным?',
          options: ['Если условие сразу ложно', 'Если забыть менять переменную условия', 'Если тело пустое', 'Никогда'], answer: 1,
          explain: 'Без изменения переменной условие всегда истинно.' },
        { type: 'output', q: 'Что выведет программа? (сумма цифр 234)', code: 'n = 234\ns = 0\nwhile n > 0:\n    s = s + n % 10\n    n = n // 10\nprint(s)', answer: '9',
          explain: '2+3+4 = 9. Отделяем цифры через %10 и //10.' },
        { type: 'assemble', q: 'Собери: вывести 1, 2, 3 через while',
          lines: ['i = 1', 'while i <= 3:', '    print(i)', '    i = i + 1'],
          explain: 'Счётчик, условие, печать и увеличение.' },
      ],
    },
  ],

  oge_for: [
    {
      id: 'oge_for_p1', title: 'Практика: for', xp: 12,
      questions: [
        { type: 'output', q: 'Что выведет программа?', code: 'for i in range(4):\n    print(i)', answer: '0\n1\n2\n3',
          explain: 'range(4) — числа 0,1,2,3.' },
        { type: 'output', q: 'Что выведет программа? (сумма 0..4)', code: 's = 0\nfor i in range(5):\n    s = s + i\nprint(s)', answer: '10',
          explain: '0+1+2+3+4 = 10.' },
        { type: 'mcq', q: 'Что даст range(3, 9, 2)?',
          options: ['3, 5, 7', '3, 5, 7, 9', '3, 6, 9', '3, 4, 5, 6, 7, 8'], answer: 0,
          explain: 'Старт 3, шаг 2: 3, 5, 7. Девять не входит.' },
        { type: 'output', q: 'Что выведет программа? (произведение 1..4)', code: 'p = 1\nfor i in range(1, 5):\n    p = p * i\nprint(p)', answer: '24',
          explain: '1*2*3*4 = 24 (факториал 4).' },
        { type: 'output', q: 'Что выведет программа?', code: 'for i in range(10, 0, -2):\n    print(i)', answer: '10\n8\n6\n4\n2',
          explain: 'От 10 вниз с шагом -2, ноль не входит.' },
        { type: 'output', q: 'Что выведет программа? (сколько чётных 1..10)', code: 'k = 0\nfor i in range(1, 11):\n    if i % 2 == 0:\n        k = k + 1\nprint(k)', answer: '5',
          explain: 'Чётные: 2,4,6,8,10 — пять чисел.' },
        { type: 'output', q: 'Что выведет программа? (сумма кратных 3 от 1 до 10)', code: 's = 0\nfor i in range(1, 11):\n    if i % 3 == 0:\n        s = s + i\nprint(s)', answer: '18',
          explain: 'Кратные 3: 3+6+9 = 18.' },
        { type: 'assemble', q: 'Собери: посчитать сумму чисел от 1 до 3',
          lines: ['s = 0', 'for i in range(1, 4):', '    s = s + i', 'print(s)'],
          explain: 'Накопитель s, цикл, вывод.' },
      ],
    },
  ],

  oge_str: [
    {
      id: 'oge_str_p1', title: 'Практика: строки', xp: 12,
      questions: [
        { type: 'output', q: 'Что выведет программа?', code: 's = "школа"\nprint(len(s))', answer: '5',
          explain: 'В слове "школа" 5 букв.' },
        { type: 'output', q: 'Что выведет программа?', code: 's = "Python"\nprint(s[1])', answer: 'y',
          explain: 'Индексы с нуля: s[1] — второй символ "y".' },
        { type: 'output', q: 'Что выведет программа?', code: 's = "код"\nprint(s[-1])', answer: 'д',
          explain: 'Индекс -1 — последний символ.' },
        { type: 'output', q: 'Что выведет программа? (подсчёт букв "а")', code: 'k = 0\nfor c in "банан":\n    if c == "а":\n        k = k + 1\nprint(k)', answer: '2',
          explain: 'В "банан" буква "а" встречается 2 раза.' },
        { type: 'output', q: 'Что выведет программа?', code: 'print("ля" * 4)', answer: 'ляляляля',
          explain: '"ля" повторяется 4 раза.' },
        { type: 'output', q: 'Что выведет программа?', code: 's = "abc"\nprint(s + "!")', answer: 'abc!',
          explain: 'Склейка строки и восклицательного знака.' },
        { type: 'mcq', q: 'Как узнать длину строки s?',
          options: ['size(s)', 'len(s)', 's.length', 'count(s)'], answer: 1,
          explain: 'len(s) возвращает количество символов.' },
        { type: 'output', q: 'Что выведет программа? (перебор)', code: 'for c in "да":\n    print(c)', answer: 'д\nа',
          explain: 'for перебирает строку по буквам, каждая с новой строки.' },
      ],
    },
  ],

  // ── ЕГЭ ──
  ege_lists: [
    {
      id: 'ege_lists_p1', title: 'Практика: списки', xp: 15,
      questions: [
        { type: 'output', q: 'Что выведет программа?', code: 'a = [4, 8, 15, 16]\nprint(a[2])', answer: '15',
          explain: 'a[2] — третий элемент (счёт с нуля).' },
        { type: 'output', q: 'Что выведет программа?', code: 'a = [1, 2, 3]\na[0] = 99\nprint(a)', answer: '[99, 2, 3]',
          explain: 'Элемент по индексу можно менять.' },
        { type: 'output', q: 'Что выведет программа?', code: 'a = [5, 3, 8, 1]\nprint(sum(a))', answer: '17',
          explain: '5+3+8+1 = 17.' },
        { type: 'output', q: 'Что выведет программа?', code: 'a = [5, 3, 8, 1]\nprint(len(a))', answer: '4',
          explain: 'В списке 4 элемента.' },
        { type: 'output', q: 'Что выведет программа? (кол-во элементов > 4)', code: 'a = [2, 7, 4, 9, 1]\nk = 0\nfor x in a:\n    if x > 4:\n        k = k + 1\nprint(k)', answer: '2',
          explain: 'Больше 4: это 7 и 9 — два элемента.' },
        { type: 'output', q: 'Что выведет программа?', code: 'a = [3, 1, 2]\na.append(5)\nprint(a)', answer: '[3, 1, 2, 5]',
          explain: 'append добавляет в конец.' },
        { type: 'output', q: 'Что выведет программа?', code: 'a = [10, 40, 20, 30]\nprint(max(a) - min(a))', answer: '30',
          explain: 'max=40, min=10, разность 30.' },
        { type: 'output', q: 'Что выведет программа? (срез)', code: 'a = [0, 1, 2, 3, 4, 5]\nprint(a[2:5])', answer: '[2, 3, 4]',
          explain: 'Срез с 2 по 4 (5 не входит).' },
        { type: 'output', q: 'Что выведет программа? (сумма чётных)', code: 'a = [1, 2, 3, 4, 5, 6]\ns = 0\nfor x in a:\n    if x % 2 == 0:\n        s = s + x\nprint(s)', answer: '12',
          explain: 'Чётные 2+4+6 = 12.' },
        { type: 'assemble', q: 'Собери: найти сумму элементов списка',
          lines: ['a = [10, 20, 30]', 'print(sum(a))'],
          explain: 'sum() сразу считает сумму.' },
      ],
    },
  ],

  ege_nested: [
    {
      id: 'ege_nested_p1', title: 'Практика: вложенные циклы', xp: 15,
      questions: [
        { type: 'output', q: 'Сколько строк выведет код?', code: 'for i in range(2):\n    for j in range(3):\n        print(i, j)', answer: '0 0\n0 1\n0 2\n1 0\n1 1\n1 2',
          explain: '2 × 3 = 6 строк, все пары (i, j).' },
        { type: 'output', q: 'Что выведет программа?', code: 'k = 0\nfor i in range(4):\n    for j in range(4):\n        k = k + 1\nprint(k)', answer: '16',
          explain: '4 × 4 = 16.' },
        { type: 'output', q: 'Что выведет программа?', code: 's = 0\nfor i in range(1, 4):\n    for j in range(1, 4):\n        s = s + i * j\nprint(s)', answer: '36',
          explain: 'Сумма произведений: (1+2+3)*(1+2+3)=6*6=36.' },
        { type: 'mcq', q: 'Внешний цикл 5 раз, внутренний 3 раза. Сколько итераций тела внутреннего?',
          options: ['8', '15', '5', '3'], answer: 1,
          explain: '5 × 3 = 15.' },
        { type: 'output', q: 'Что выведет программа?', code: 'for i in range(3):\n    for j in range(i + 1):\n        print("*", end="")\n    print()', answer: '*\n**\n***',
          explain: 'Треугольник: в строке i выводится i+1 звёздочек.' },
      ],
    },
  ],

  ege_func: [
    {
      id: 'ege_func_p1', title: 'Практика: функции', xp: 15,
      questions: [
        { type: 'output', q: 'Что выведет программа?', code: 'def f(x):\n    return x + 10\nprint(f(5))', answer: '15',
          explain: 'f(5) возвращает 5 + 10 = 15.' },
        { type: 'output', q: 'Что выведет программа?', code: 'def mult(a, b):\n    return a * b\nprint(mult(3, 6))', answer: '18',
          explain: 'mult(3, 6) = 3 * 6 = 18.' },
        { type: 'output', q: 'Что выведет программа?', code: 'def f(n):\n    return n * n\nprint(f(2) + f(3))', answer: '13',
          explain: 'f(2)=4, f(3)=9, сумма 13.' },
        { type: 'output', q: 'Что выведет программа?', code: 'def maxi(a, b):\n    if a > b:\n        return a\n    return b\nprint(maxi(7, 12))', answer: '12',
          explain: 'Функция возвращает большее: 12.' },
        { type: 'output', q: 'Что выведет программа?', code: 'def znak(x):\n    if x > 0:\n        return "плюс"\n    else:\n        return "минус"\nprint(znak(-4))', answer: 'минус',
          explain: '-4 не больше 0, возвращается "минус".' },
        { type: 'mcq', q: 'Чем return отличается от print?',
          options: ['Ничем', 'return возвращает значение в программу, print только показывает', 'print быстрее', 'return выводит на экран'], answer: 1,
          explain: 'return отдаёт результат для дальнейшего использования, print только печатает.' },
        { type: 'output', q: 'Что выведет программа?', code: 'def summa(a, b, c):\n    return a + b + c\nprint(summa(1, 2, 3))', answer: '6',
          explain: 'Три параметра: 1+2+3 = 6.' },
        { type: 'assemble', q: 'Собери функцию, возвращающую удвоенное число',
          lines: ['def double(x):', '    return x * 2', 'print(double(9))'],
          explain: 'def, тело с return, вызов.' },
      ],
    },
  ],

  ege_str2: [
    {
      id: 'ege_str2_p1', title: 'Практика: строки ЕГЭ', xp: 15,
      questions: [
        { type: 'output', q: 'Что выведет программа?', code: 's = "программа"\nprint(s[0:4])', answer: 'прог',
          explain: 'Срез s[0:4] — символы с 0 по 3.' },
        { type: 'output', q: 'Что выведет программа?', code: 's = "abcdef"\nprint(s[2:])', answer: 'cdef',
          explain: 'Срез без правой границы — до конца.' },
        { type: 'output', q: 'Что выведет программа?', code: 's = "abcdef"\nprint(s[:3])', answer: 'abc',
          explain: 'Срез без левой границы — с начала.' },
        { type: 'output', q: 'Что выведет программа?', code: 's = "Привет"\nprint(s.lower())', answer: 'привет',
          explain: 'lower() делает буквы строчными.' },
        { type: 'output', q: 'Что выведет программа?', code: 's = "a-b-c-d"\nprint(s.split("-"))', answer: "['a', 'b', 'c', 'd']",
          explain: 'split("-") разбивает по дефису в список.' },
        { type: 'output', q: 'Что выведет программа?', code: 'a = ["x", "y", "z"]\nprint("+".join(a))', answer: 'x+y+z',
          explain: 'join склеивает список в строку через разделитель.' },
        { type: 'output', q: 'Что выведет программа?', code: 's = "рама мала"\nprint(s.count("а"))', answer: '4',
          explain: 'Буква "а" в "рама мала": р-А-м-А м-А-л-А — четыре раза.' },
        { type: 'output', q: 'Что выведет программа?', code: 's = "hello"\nprint(s.upper())', answer: 'HELLO',
          explain: 'upper() — заглавные буквы.' },
        { type: 'output', q: 'Что выведет программа?', code: 's = "abcabc"\nprint(s.find("c"))', answer: '2',
          explain: 'find возвращает индекс первого вхождения "c" — это 2.' },
      ],
    },
  ],

  ege_dict: [
    {
      id: 'ege_dict_p1', title: 'Практика: словари', xp: 15,
      questions: [
        { type: 'output', q: 'Что выведет программа?', code: 'd = {"кот": 3, "пёс": 5}\nprint(d["пёс"])', answer: '5',
          explain: 'Значение по ключу "пёс" равно 5.' },
        { type: 'output', q: 'Что выведет программа?', code: 'd = {"a": 1}\nd["b"] = 2\nprint(len(d))', answer: '2',
          explain: 'Добавили ключ "b", теперь 2 пары.' },
        { type: 'output', q: 'Что выведет программа?', code: 'd = {"x": 10}\nd["x"] = d["x"] + 5\nprint(d["x"])', answer: '15',
          explain: 'Значение по ключу "x" увеличили на 5.' },
        { type: 'output', q: 'Что выведет программа? (уникальные)', code: 's = {1, 1, 2, 2, 2, 3}\nprint(len(s))', answer: '3',
          explain: 'Множество хранит только уникальные: 1, 2, 3.' },
        { type: 'output', q: 'Что выведет программа? (частота символов)', code: 'd = {}\nfor c in "aabbb":\n    d[c] = d.get(c, 0) + 1\nprint(d["b"])', answer: '3',
          explain: '"b" встречается 3 раза.' },
        { type: 'mcq', q: 'Чем словарь отличается от списка?',
          options: ['Ничем', 'Доступ по ключу, а не по индексу', 'Словарь быстрее', 'В словаре только числа'], answer: 1,
          explain: 'В словаре доступ к значению по ключу (может быть строкой).' },
        { type: 'output', q: 'Что выведет программа?', code: 's = {5, 3, 5, 1, 3}\nprint(len(s))', answer: '3',
          explain: 'Уникальные значения: 5, 3, 1 — три штуки.' },
      ],
    },
  ],

  ege_lib: [
    {
      id: 'ege_lib_p1', title: 'Практика: библиотеки', xp: 15,
      questions: [
        { type: 'output', q: 'Что выведет программа?', code: 'import math\nprint(math.sqrt(25))', answer: '5.0',
          explain: 'Квадратный корень из 25 = 5.0.' },
        { type: 'output', q: 'Что выведет программа?', code: 'import math\nprint(math.floor(4.7))', answer: '4',
          explain: 'floor округляет вниз до 4.' },
        { type: 'output', q: 'Что выведет программа?', code: 'import math\nprint(math.ceil(4.2))', answer: '5',
          explain: 'ceil округляет вверх до 5.' },
        { type: 'output', q: 'Что выведет программа?', code: 'import math\nprint(math.factorial(5))', answer: '120',
          explain: '5! = 1*2*3*4*5 = 120.' },
        { type: 'mcq', q: 'Что делает abs(-8)?', code: 'print(abs(-8))',
          options: ['-8', '8', '0', 'ошибка'], answer: 1,
          explain: 'abs — модуль числа, |-8| = 8.' },
        { type: 'output', q: 'Что выведет программа?', code: 'print(round(3.7))', answer: '4',
          explain: 'round округляет до ближайшего целого: 4.' },
        { type: 'output', q: 'Что выведет программа?', code: 'import math\nprint(math.sqrt(9) + 1)', answer: '4.0',
          explain: 'sqrt(9)=3.0, плюс 1 = 4.0.' },
      ],
    },
  ],

  ege_algo: [
    {
      id: 'ege_algo_p1', title: 'Практика: задачи ЕГЭ', xp: 20,
      questions: [
        { type: 'output', q: 'Что выведет программа? (сумма цифр 1234)', code: 'n = 1234\ns = 0\nwhile n > 0:\n    s = s + n % 10\n    n = n // 10\nprint(s)', answer: '10',
          explain: '1+2+3+4 = 10.' },
        { type: 'output', q: 'Что выведет программа? (кол-во цифр 5060)', code: 'n = 5060\nk = 0\nwhile n > 0:\n    k = k + 1\n    n = n // 10\nprint(k)', answer: '4',
          explain: 'В числе 5060 четыре цифры.' },
        { type: 'output', q: 'Что выведет программа? (минимум)', code: 'a = [7, 2, 9, 1, 5]\nm = a[0]\nfor x in a:\n    if x < m:\n        m = x\nprint(m)', answer: '1',
          explain: 'Поиск минимума перебором: 1.' },
        { type: 'output', q: 'Что выведет программа? (простое ли 7)', code: 'n = 7\nk = 0\nfor d in range(1, n + 1):\n    if n % d == 0:\n        k = k + 1\nprint(k)', answer: '2',
          explain: 'У 7 два делителя (1 и 7) — значит простое.' },
        { type: 'output', q: 'Что выведет программа? (реверс числа 123)', code: 'n = 123\nr = 0\nwhile n > 0:\n    r = r * 10 + n % 10\n    n = n // 10\nprint(r)', answer: '321',
          explain: 'Переворот числа: 123 → 321.' },
        { type: 'output', q: 'Что выведет программа? (макс из списка)', code: 'a = [3, 8, 2, 8, 5]\nm = a[0]\nfor x in a:\n    if x > m:\n        m = x\nprint(m)', answer: '8',
          explain: 'Наибольшее значение — 8.' },
        { type: 'output', q: 'Что выведет программа? (сколько положительных)', code: 'a = [-2, 5, -1, 3, 0, 7]\nk = 0\nfor x in a:\n    if x > 0:\n        k = k + 1\nprint(k)', answer: '3',
          explain: 'Положительные: 5, 3, 7 — три числа.' },
      ],
    },
  ],
};
