// projects.js — мини-проекты: пошаговая сборка настоящей программы.
// Каждый проект = цепочка шагов (обычные задания) + финальный код + пример запуска.
// Проверка каждого шага как в уроке, без реального запуска (финал выверен на Python).

export const PROJECTS = [
  {
    id: 'proj_calc',
    title: 'Калькулятор',
    icon: '🧮',
    color: '#4ade80',
    unlockAfter: 'oge_input',
    desc: 'Считает два числа и выводит сумму',
    intro: 'Соберём программу, которая считывает два числа и складывает их. Погнали по шагам!',
    steps: [
      { type: 'mcq', q: 'Шаг 1. Как считать с клавиатуры ЦЕЛОЕ число?',
        options: ['int(input())', 'input()', 'str(input())', 'number()'], answer: 0,
        explain: 'int(input()) считывает строку и превращает её в целое число.' },
      { type: 'assemble', q: 'Шаг 2. Считай первое число в переменную a',
        lines: ['a = int(input())'],
        explain: 'Кладём считанное число в a.' },
      { type: 'assemble', q: 'Шаг 3. Считай второе число в переменную b',
        lines: ['b = int(input())'],
        explain: 'То же самое для b.' },
      { type: 'mcq', q: 'Шаг 4. Как вывести их сумму?',
        options: ['print(a + b)', 'print("a + b")', 'print(a, b)', 'sum(a, b)'], answer: 0,
        explain: 'print(a + b) сложит числа и выведет результат.' },
    ],
    finalCode: 'a = int(input())\nb = int(input())\nprint(a + b)',
    example: { input: '2\n3', output: '5' },
  },

  {
    id: 'proj_table',
    title: 'Таблица умножения',
    icon: '✖️',
    color: '#22d3ee',
    unlockAfter: 'oge_for',
    desc: 'Печатает таблицу умножения для числа',
    intro: 'Соберём программу, которая печатает таблицу умножения для введённого числа. Здесь пригодится цикл for.',
    steps: [
      { type: 'assemble', q: 'Шаг 1. Считай число n',
        lines: ['n = int(input())'],
        explain: 'Число, для которого печатаем таблицу.' },
      { type: 'mcq', q: 'Шаг 2. Какой цикл повторит для i от 1 до 5?',
        options: ['for i in range(1, 6):', 'for i in range(5):', 'for i in range(1, 5):', 'while i < 5:'], answer: 0,
        explain: 'range(1, 6) даёт 1,2,3,4,5 — правая граница 6 не входит.' },
      { type: 'assemble', q: 'Шаг 3. Собери тело: выведи строку таблицы',
        lines: ['for i in range(1, 6):', '    print(n, "x", i, "=", n * i)'],
        explain: 'Для каждого i печатаем n, знак умножения, i и произведение.' },
    ],
    finalCode: 'n = int(input())\nfor i in range(1, 6):\n    print(n, "x", i, "=", n * i)',
    example: { input: '3', output: '3 x 1 = 3\n3 x 2 = 6\n3 x 3 = 9\n3 x 4 = 12\n3 x 5 = 15' },
  },

  {
    id: 'proj_caesar',
    title: 'Шифр Цезаря',
    icon: '🔐',
    color: '#a78bfa',
    unlockAfter: 'oge_str',
    desc: 'Шифрует слово сдвигом букв',
    intro: 'Шифр Цезаря сдвигает каждую букву на несколько позиций в алфавите. ord(c) даёт номер буквы, chr(число) — букву обратно.',
    steps: [
      { type: 'mcq', q: 'Шаг 1. Что делает chr(ord("a") + 1)?',
        options: ['Сдвигает букву на 1 → "b"', 'Удваивает', 'Ошибка', 'Выводит 1'], answer: 0,
        explain: 'ord("a")=97, +1=98, chr(98)="b". Так буква сдвигается вперёд.' },
      { type: 'assemble', q: 'Шаг 2. Считай слово и величину сдвига',
        lines: ['s = input()', 'k = int(input())'],
        explain: 'Слово s и число сдвига k.' },
      { type: 'assemble', q: 'Шаг 3. Заведи пустой результат и собери цикл сдвига',
        lines: ['r = ""', 'for c in s:', '    r = r + chr(ord(c) + k)'],
        explain: 'Проходим по буквам, каждую сдвигаем на k и добавляем в r.' },
      { type: 'mcq', q: 'Шаг 4. Как вывести результат?',
        options: ['print(r)', 'print("r")', 'print(s)', 'print(k)'], answer: 0,
        explain: 'В r накопился зашифрованный текст — выводим его.' },
    ],
    finalCode: 's = input()\nk = int(input())\nr = ""\nfor c in s:\n    r = r + chr(ord(c) + k)\nprint(r)',
    example: { input: 'abc\n1', output: 'bcd' },
  },

  {
    id: 'proj_stats',
    title: 'Статистика оценок',
    icon: '📊',
    color: '#f59e0b',
    unlockAfter: 'ege_lists',
    desc: 'Средний балл, максимум, число пятёрок',
    intro: 'Есть список оценок. Посчитаем средний балл, лучшую оценку и сколько пятёрок. Пригодятся sum, len, max и count.',
    steps: [
      { type: 'mcq', q: 'Шаг 1. Как найти сумму всех оценок списка a?',
        options: ['sum(a)', 'len(a)', 'max(a)', 'a.sum()'], answer: 0,
        explain: 'sum(a) складывает все элементы списка.' },
      { type: 'assemble', q: 'Шаг 2. Выведи средний балл (округли до 2 знаков)',
        lines: ['print("Средний:", round(sum(a) / len(a), 2))'],
        explain: 'Средний = сумма / количество. round(..., 2) — два знака после запятой.' },
      { type: 'mcq', q: 'Шаг 3. Как посчитать количество пятёрок в списке?',
        options: ['a.count(5)', 'a.index(5)', 'sum(5)', 'len(5)'], answer: 0,
        explain: 'count(5) считает, сколько раз 5 встречается в списке.' },
    ],
    finalCode: 'a = [5, 4, 5, 3, 4, 5]\nprint("Средний:", round(sum(a) / len(a), 2))\nprint("Максимум:", max(a))\nprint("Пятёрок:", a.count(5))',
    example: { input: '(список [5, 4, 5, 3, 4, 5])', output: 'Средний: 4.33\nМаксимум: 5\nПятёрок: 3' },
  },

  {
    id: 'proj_guess',
    title: 'Угадай число',
    icon: '🎯',
    color: '#22d3ee',
    unlockAfter: 'oge_if',
    desc: 'Подсказывает больше/меньше загаданного',
    intro: 'Программа загадала число. Игрок вводит ответ, а мы подсказываем: угадал, больше или меньше. Нужны if / elif / else.',
    steps: [
      { type: 'assemble', q: 'Шаг 1. Считай ответ игрока',
        lines: ['otvet = int(input())'],
        explain: 'Число, которое ввёл игрок.' },
      { type: 'assemble', q: 'Шаг 2. Собери проверку с тремя ветками',
        lines: ['if otvet == zagadka:', '    print("Угадал!")', 'elif otvet < zagadka:', '    print("Больше")', 'else:', '    print("Меньше")'],
        explain: 'Три случая: равно — угадал; меньше — надо больше; иначе — меньше.' },
    ],
    finalCode: 'zagadka = 7\notvet = int(input())\nif otvet == zagadka:\n    print("Угадал!")\nelif otvet < zagadka:\n    print("Больше")\nelse:\n    print("Меньше")',
    example: { input: '5', output: 'Больше' },
  },

  {
    id: 'proj_password',
    title: 'Проверка пароля',
    icon: '🔑',
    color: '#a78bfa',
    unlockAfter: 'oge_str',
    desc: 'Оценивает надёжность по длине',
    intro: 'Простая проверка: пароль надёжный, если в нём хотя бы 6 символов. Нужны len и if / else.',
    steps: [
      { type: 'mcq', q: 'Шаг 1. Как узнать длину строки p?',
        options: ['len(p)', 'p.length', 'size(p)', 'count(p)'], answer: 0,
        explain: 'len(p) возвращает количество символов.' },
      { type: 'assemble', q: 'Шаг 2. Считай пароль и собери проверку длины',
        lines: ['p = input()', 'if len(p) >= 6:', '    print("Надёжный")', 'else:', '    print("Слабый")'],
        explain: 'Если длина 6 и больше — надёжный, иначе слабый.' },
    ],
    finalCode: 'p = input()\nif len(p) >= 6:\n    print("Надёжный")\nelse:\n    print("Слабый")',
    example: { input: 'abcdef', output: 'Надёжный' },
  },
];
