// projects.js — мини-проекты: пошаговая сборка настоящей программы.
// Каждый проект = цепочка шагов (обычные задания) + финальный код + пример запуска.
// Проверка каждого шага как в уроке, без реального запуска (финал выверен на Python).

export const PROJECTS = [
  {
    id: 'proj_calc',
    title: 'Калькулятор',
    icon: '🧮',
    color: '#4ade80',
    unlockAfter: 'oge_input',
    desc: 'Считает два числа и выводит сумму',
    intro: 'Соберём программу, которая считывает два числа и складывает их. Погнали по шагам!',
    steps: [
      { type: 'mcq', q: 'Шаг 1. Как считать с клавиатуры ЦЕЛОЕ число?',
        options: ['int(input())', 'input()', 'str(input())', 'number()'], answer: 0,
        explain: 'int(input()) считывает строку и превращает её в целое число.' },
      { type: 'assemble', q: 'Шаг 2. Собери строку: считай первое число в a',
        tokens: ['a', '=', 'int(input())'],
        explain: 'Слева переменная a, потом =, потом int(input()).' },
      { type: 'assemble', q: 'Шаг 3. Собери строку: считай второе число в b',
        tokens: ['b', '=', 'int(input())'],
        explain: 'То же самое для b.' },
      { type: 'mcq', q: 'Шаг 4. Как вывести их сумму?',
        options: ['print(a + b)', 'print("a + b")', 'print(a, b)', 'sum(a, b)'], answer: 0,
        explain: 'print(a + b) сложит числа и выведет результат.' },
    ],
    finalCode: 'a = int(input())\nb = int(input())\nprint(a + b)',
    example: { input: '2\n3', output: '5' },
  },

  {
    id: 'proj_table',
    title: 'Таблица умножения',
    icon: '✖️',
    color: '#22d3ee',
    unlockAfter: 'oge_for',
    desc: 'Печатает таблицу умножения для числа',
    intro: 'Соберём программу, которая печатает таблицу умножения для введённого числа. Здесь пригодится цикл for.',
    steps: [
      { type: 'assemble', q: 'Шаг 1. Собери строку: считай число n',
        tokens: ['n', '=', 'int(input())'],
        explain: 'n = int(input()) — считать целое число.' },
      { type: 'mcq', q: 'Шаг 2. Какой цикл повторит для i от 1 до 5?',
        options: ['for i in range(1, 6):', 'for i in range(5):', 'for i in range(1, 5):', 'while i < 5:'], answer: 0,
        explain: 'range(1, 6) даёт 1,2,3,4,5 — правая граница 6 не входит.' },
      { type: 'assemble', q: 'Шаг 3. Собери тело: выведи строку таблицы',
        lines: ['for i in range(1, 6):', '    print(n, "x", i, "=", n * i)'],
        explain: 'Для каждого i печатаем n, знак умножения, i и произведение.' },
    ],
    finalCode: 'n = int(input())\nfor i in range(1, 6):\n    print(n, "x", i, "=", n * i)',
    example: { input: '3', output: '3 x 1 = 3\n3 x 2 = 6\n3 x 3 = 9\n3 x 4 = 12\n3 x 5 = 15' },
  },

  {
    id: 'proj_caesar',
    title: 'Шифр Цезаря',
    icon: '🔐',
    color: '#a78bfa',
    unlockAfter: 'oge_str',
    desc: 'Шифрует слово сдвигом букв',
    intro: 'Шифр Цезаря сдвигает каждую букву на несколько позиций в алфавите. ord(c) даёт номер буквы, chr(число) — букву обратно.',
    steps: [
      { type: 'mcq', q: 'Шаг 1. Что делает chr(ord("a") + 1)?',
        options: ['Сдвигает букву на 1 → "b"', 'Удваивает', 'Ошибка', 'Выводит 1'], answer: 0,
        explain: 'ord("a")=97, +1=98, chr(98)="b". Так буква сдвигается вперёд.' },
      { type: 'assemble', q: 'Шаг 2. Считай слово и величину сдвига',
        lines: ['s = input()', 'k = int(input())'],
        explain: 'Слово s и число сдвига k.' },
      { type: 'assemble', q: 'Шаг 3. Заведи пустой результат и собери цикл сдвига',
        lines: ['r = ""', 'for c in s:', '    r = r + chr(ord(c) + k)'],
        explain: 'Проходим по буквам, каждую сдвигаем на k и добавляем в r.' },
      { type: 'mcq', q: 'Шаг 4. Как вывести результат?',
        options: ['print(r)', 'print("r")', 'print(s)', 'print(k)'], answer: 0,
        explain: 'В r накопился зашифрованный текст — выводим его.' },
    ],
    finalCode: 's = input()\nk = int(input())\nr = ""\nfor c in s:\n    r = r + chr(ord(c) + k)\nprint(r)',
    example: { input: 'abc\n1', output: 'bcd' },
  },

  {
    id: 'proj_stats',
    title: 'Статистика оценок',
    icon: '📊',
    color: '#f59e0b',
    unlockAfter: 'ege_lists',
    desc: 'Средний балл, максимум, число пятёрок',
    intro: 'Есть список оценок. Посчитаем средний балл, лучшую оценку и сколько пятёрок. Пригодятся sum, len, max и count.',
    steps: [
      { type: 'mcq', q: 'Шаг 1. Как найти сумму всех оценок списка a?',
        options: ['sum(a)', 'len(a)', 'max(a)', 'a.sum()'], answer: 0,
        explain: 'sum(a) складывает все элементы списка.' },
      { type: 'mcq', q: 'Шаг 2. Как вывести средний балл (сумма / количество, округлить до 2 знаков)?',
        options: [
          'print("Средний:", round(sum(a) / len(a), 2))',
          'print("Средний:", sum(a) / len(a))',
          'print("Средний:", round(sum(a), 2))',
          'print("Средний:", sum(a) // len(a))',
        ], answer: 0,
        explain: 'Средний = sum(a) / len(a). round(..., 2) округляет до 2 знаков. Вариант с // дал бы целое, без round — длинную дробь.' },
      { type: 'mcq', q: 'Шаг 3. Как посчитать количество пятёрок в списке?',
        options: ['a.count(5)', 'a.index(5)', 'sum(5)', 'len(5)'], answer: 0,
        explain: 'count(5) считает, сколько раз 5 встречается в списке.' },
    ],
    finalCode: 'a = [5, 4, 5, 3, 4, 5]\nprint("Средний:", round(sum(a) / len(a), 2))\nprint("Максимум:", max(a))\nprint("Пятёрок:", a.count(5))',
    example: { input: '(список [5, 4, 5, 3, 4, 5])', output: 'Средний: 4.33\nМаксимум: 5\nПятёрок: 3' },
  },

  {
    id: 'proj_guess',
    title: 'Угадай число',
    icon: '🎯',
    color: '#22d3ee',
    unlockAfter: 'oge_if',
    desc: 'Подсказывает больше/меньше загаданного',
    intro: 'Программа загадала число. Игрок вводит ответ, а мы подсказываем: угадал, больше или меньше. Нужны if / elif / else.',
    steps: [
      { type: 'assemble', q: 'Шаг 1. Собери строку: считай ответ игрока',
        tokens: ['otvet', '=', 'int(input())'],
        explain: 'otvet = int(input()) — считать число, введённое игроком.' },
      { type: 'assemble', q: 'Шаг 2. Собери проверку с тремя ветками',
        lines: ['if otvet == zagadka:', '    print("Угадал!")', 'elif otvet < zagadka:', '    print("Больше")', 'else:', '    print("Меньше")'],
        explain: 'Три случая: равно — угадал; меньше — надо больше; иначе — меньше.' },
    ],
    finalCode: 'zagadka = 7\notvet = int(input())\nif otvet == zagadka:\n    print("Угадал!")\nelif otvet < zagadka:\n    print("Больше")\nelse:\n    print("Меньше")',
    example: { input: '5', output: 'Больше' },
  },

  {
    id: 'proj_password',
    title: 'Проверка пароля',
    icon: '🔑',
    color: '#a78bfa',
    unlockAfter: 'oge_str',
    desc: 'Оценивает надёжность по длине',
    intro: 'Простая проверка: пароль надёжный, если в нём хотя бы 6 символов. Нужны len и if / else.',
    steps: [
      { type: 'mcq', q: 'Шаг 1. Как узнать длину строки p?',
        options: ['len(p)', 'p.length', 'size(p)', 'count(p)'], answer: 0,
        explain: 'len(p) возвращает количество символов.' },
      { type: 'assemble', q: 'Шаг 2. Считай пароль и собери проверку длины',
        lines: ['p = input()', 'if len(p) >= 6:', '    print("Надёжный")', 'else:', '    print("Слабый")'],
        explain: 'Если длина 6 и больше — надёжный, иначе слабый.' },
    ],
    finalCode: 'p = input()\nif len(p) >= 6:\n    print("Надёжный")\nelse:\n    print("Слабый")',
    example: { input: 'abcdef', output: 'Надёжный' },
  },

  // ══════════ СРЕДНИЙ УРОВЕНЬ ══════════
  {
    id: 'proj_digitsum',
    title: 'Сумма цифр числа',
    icon: '➕',
    color: '#22d3ee',
    unlockAfter: 'oge_while',
    desc: 'Складывает все цифры числа',
    intro: 'Классика ЕГЭ: разобрать число на цифры и сложить их. Приём — n % 10 (последняя цифра) и n // 10 (убрать её).',
    steps: [
      { type: 'assemble', q: 'Шаг 1. Собери: считай число n',
        tokens: ['n', '=', 'int(input())'],
        explain: 'Считываем целое число.' },
      { type: 'mcq', q: 'Шаг 2. Как получить последнюю цифру числа n?',
        options: ['n % 10', 'n // 10', 'n / 10', 'n * 10'], answer: 0,
        explain: 'Остаток от деления на 10 — это последняя цифра.' },
      { type: 'mcq', q: 'Шаг 3. Как убрать последнюю цифру?',
        options: ['n // 10', 'n % 10', 'n - 10', 'n / 10'], answer: 0,
        explain: 'Целочисленное деление на 10 отбрасывает последнюю цифру.' },
      { type: 'assemble', q: 'Шаг 4. Собери цикл суммирования цифр',
        lines: ['s = 0', 'while n > 0:', '    s = s + n % 10', '    n = n // 10', 'print(s)'],
        explain: 'Пока число не 0: прибавляем последнюю цифру и отрезаем её.' },
    ],
    finalCode: 'n = int(input())\ns = 0\nwhile n > 0:\n    s = s + n % 10\n    n = n // 10\nprint(s)',
    example: { input: '253', output: '10' },
  },

  {
    id: 'proj_reverse',
    title: 'Переворот числа',
    icon: '🔄',
    color: '#22d3ee',
    unlockAfter: 'oge_while',
    desc: 'Разворачивает число задом наперёд',
    intro: 'Собираем число заново с конца: r = r * 10 + последняя цифра. Так 123 превращается в 321.',
    steps: [
      { type: 'assemble', q: 'Шаг 1. Собери: считай число n',
        tokens: ['n', '=', 'int(input())'],
        explain: 'Считываем число.' },
      { type: 'mcq', q: 'Шаг 2. Как «пристроить» цифру d к результату r справа?',
        options: ['r = r * 10 + d', 'r = r + d', 'r = d * 10', 'r = r + d * 10'], answer: 0,
        explain: 'Сдвигаем r на разряд влево (×10) и добавляем новую цифру.' },
      { type: 'assemble', q: 'Шаг 3. Собери цикл переворота',
        lines: ['r = 0', 'while n > 0:', '    r = r * 10 + n % 10', '    n = n // 10', 'print(r)'],
        explain: 'Каждый шаг забираем последнюю цифру n и пристраиваем к r.' },
    ],
    finalCode: 'n = int(input())\nr = 0\nwhile n > 0:\n    r = r * 10 + n % 10\n    n = n // 10\nprint(r)',
    example: { input: '123', output: '321' },
  },

  {
    id: 'proj_palindrome',
    title: 'Палиндром',
    icon: '🪞',
    color: '#a78bfa',
    unlockAfter: 'oge_str',
    desc: 'Проверяет, читается ли слово одинаково',
    intro: 'Палиндром читается одинаково в обе стороны (казак, шалаш). Проверка простая: строка равна своему перевороту s[::-1].',
    steps: [
      { type: 'mcq', q: 'Шаг 1. Как перевернуть строку s?',
        options: ['s[::-1]', 's.reverse()', 's[-1]', 's * -1'], answer: 0,
        explain: 'Срез s[::-1] переворачивает строку.' },
      { type: 'assemble', q: 'Шаг 2. Собери проверку палиндрома',
        lines: ['s = input()', 'if s == s[::-1]:', '    print("Да")', 'else:', '    print("Нет")'],
        explain: 'Если строка равна своему перевороту — это палиндром.' },
    ],
    finalCode: 's = input()\nif s == s[::-1]:\n    print("Да")\nelse:\n    print("Нет")',
    example: { input: 'казак', output: 'Да' },
  },

  {
    id: 'proj_prime',
    title: 'Простое число?',
    icon: '🔎',
    color: '#a78bfa',
    unlockAfter: 'oge_for',
    desc: 'Определяет, простое ли число',
    intro: 'Число простое, если у него ровно 2 делителя (1 и оно само). Посчитаем делители и проверим.',
    steps: [
      { type: 'assemble', q: 'Шаг 1. Собери: считай число n',
        tokens: ['n', '=', 'int(input())'],
        explain: 'Считываем число для проверки.' },
      { type: 'assemble', q: 'Шаг 2. Собери подсчёт делителей',
        lines: ['k = 0', 'for d in range(1, n + 1):', '    if n % d == 0:', '        k = k + 1'],
        explain: 'Перебираем от 1 до n, считаем делители.' },
      { type: 'mcq', q: 'Шаг 3. Сколько делителей у простого числа?',
        options: ['Ровно 2', 'Ровно 1', 'Больше 2', 'Ноль'], answer: 0,
        explain: 'Простое делится только на 1 и на себя — 2 делителя.' },
      { type: 'assemble', q: 'Шаг 4. Собери вывод результата',
        lines: ['if k == 2:', '    print("Простое")', 'else:', '    print("Составное")'],
        explain: 'k == 2 → простое, иначе составное.' },
    ],
    finalCode: 'n = int(input())\nk = 0\nfor d in range(1, n + 1):\n    if n % d == 0:\n        k = k + 1\nif k == 2:\n    print("Простое")\nelse:\n    print("Составное")',
    example: { input: '7', output: 'Простое' },
  },

  {
    id: 'proj_pifagor',
    title: 'Таблица Пифагора',
    icon: '📐',
    color: '#f59e0b',
    unlockAfter: 'ege_nested',
    desc: 'Печатает таблицу 3×3 произведений',
    intro: 'Вложенные циклы: внешний идёт по строкам, внутренний по столбцам. Печатаем произведение i·j.',
    steps: [
      { type: 'mcq', q: 'Шаг 1. Что делает end=" " в print?',
        options: ['Печатает в ту же строку через пробел', 'Завершает программу', 'Переносит строку', 'Ставит точку'], answer: 0,
        explain: 'end=" " заменяет перенос строки на пробел — вывод идёт в одну строку.' },
      { type: 'assemble', q: 'Шаг 2. Собери двойной цикл с выводом произведений',
        lines: ['for i in range(1, 4):', '    for j in range(1, 4):', '        print(i * j, end=" ")', '    print()'],
        explain: 'Внешний цикл — строки, внутренний — столбцы. print() после внутреннего переносит строку.' },
    ],
    finalCode: 'for i in range(1, 4):\n    for j in range(1, 4):\n        print(i * j, end=" ")\n    print()',
    example: { input: '(нет ввода)', output: '1 2 3 \n2 4 6 \n3 6 9 ' },
  },

  // ══════════ ЕГЭ-УРОВЕНЬ ══════════
  {
    id: 'proj_divcount',
    title: 'Количество делителей',
    icon: '🔢',
    color: '#7c3aed',
    unlockAfter: 'ege_task25',
    desc: 'Считает все делители числа',
    intro: 'Основа задачи 25. Перебираем возможные делители и считаем те, на которые число делится нацело.',
    steps: [
      { type: 'assemble', q: 'Шаг 1. Собери: считай число n',
        tokens: ['n', '=', 'int(input())'],
        explain: 'Число, у которого считаем делители.' },
      { type: 'mcq', q: 'Шаг 2. Как проверить, что d — делитель n?',
        options: ['n % d == 0', 'n // d == 0', 'n / d == 0', 'n * d == 0'], answer: 0,
        explain: 'Делитель — остаток от деления равен 0.' },
      { type: 'assemble', q: 'Шаг 3. Собери подсчёт делителей',
        lines: ['k = 0', 'for d in range(1, n + 1):', '    if n % d == 0:', '        k = k + 1', 'print(k)'],
        explain: 'Перебор от 1 до n, счётчик подходящих.' },
    ],
    finalCode: 'n = int(input())\nk = 0\nfor d in range(1, n + 1):\n    if n % d == 0:\n        k = k + 1\nprint(k)',
    example: { input: '12', output: '6' },
  },

  {
    id: 'proj_charfreq',
    title: 'Частота символов',
    icon: '📊',
    color: '#ec4899',
    unlockAfter: 'ege_dict',
    desc: 'Считает, сколько раз встречается каждый символ',
    intro: 'Словарь — идеальный инструмент для подсчёта частот. d.get(c, 0) даёт текущее число или 0, если символа ещё не было.',
    steps: [
      { type: 'assemble', q: 'Шаг 1. Собери: считай строку и заведи пустой словарь',
        lines: ['s = input()', 'd = {}'],
        explain: 'Строка s и пустой словарь d для подсчёта.' },
      { type: 'mcq', q: 'Шаг 2. Что вернёт d.get(c, 0), если символа c ещё нет?',
        options: ['0', 'Ошибку', 'None', 'Пустую строку'], answer: 0,
        explain: 'get с двумя аргументами возвращает второй (0), если ключа нет.' },
      { type: 'assemble', q: 'Шаг 3. Собери цикл подсчёта и вывод',
        lines: ['for c in s:', '    d[c] = d.get(c, 0) + 1', 'print(d)'],
        explain: 'Для каждого символа увеличиваем его счётчик на 1.' },
    ],
    finalCode: 's = input()\nd = {}\nfor c in s:\n    d[c] = d.get(c, 0) + 1\nprint(d)',
    example: { input: 'aab', output: "{'a': 2, 'b': 1}" },
  },

  {
    id: 'proj_distance',
    title: 'Расстояние между точками',
    icon: '📏',
    color: '#7c3aed',
    unlockAfter: 'ege_geometry',
    desc: 'Считает расстояние по теореме Пифагора',
    intro: 'Задача 27. Расстояние между точками — корень из суммы квадратов разностей координат. Есть готовая math.dist.',
    steps: [
      { type: 'mcq', q: 'Шаг 1. По какой формуле расстояние между точками?',
        options: ['√((x2-x1)² + (y2-y1)²)', '(x2-x1) + (y2-y1)', 'x1·y2', '(x2+x1)/2'], answer: 0,
        explain: 'Теорема Пифагора для разностей координат.' },
      { type: 'assemble', q: 'Шаг 2. Собери: подключи dist и задай две точки',
        lines: ['from math import dist', 'a = [0, 0]', 'b = [3, 4]'],
        explain: 'Импортируем готовую функцию и задаём точки.' },
      { type: 'mcq', q: 'Шаг 3. Как вывести расстояние между a и b?',
        options: ['print(dist(a, b))', 'print(dist(a) + dist(b))', 'print(a - b)', 'print(dist(a))'], answer: 0,
        explain: 'dist(a, b) сразу считает расстояние между двумя точками.' },
    ],
    finalCode: 'from math import dist\na = [0, 0]\nb = [3, 4]\nprint(dist(a, b))',
    example: { input: '(точки [0,0] и [3,4])', output: '5.0' },
  },

  {
    id: 'proj_gcd',
    title: 'НОД (алгоритм Евклида)',
    icon: '🧩',
    color: '#ec4899',
    unlockAfter: 'oge_while',
    desc: 'Наибольший общий делитель двух чисел',
    intro: 'Древний алгоритм Евклида: пока второе число не 0, заменяем пару (a, b) на (b, остаток a на b). Останется НОД.',
    steps: [
      { type: 'assemble', q: 'Шаг 1. Собери: считай два числа a и b',
        lines: ['a = int(input())', 'b = int(input())'],
        explain: 'Два числа, для которых ищем НОД.' },
      { type: 'mcq', q: 'Шаг 2. Пока b > 0, на что меняем пару (a, b)?',
        options: ['a, b = b, a % b', 'a, b = b, a', 'a, b = a % b, b', 'a, b = a, b % a'], answer: 0,
        explain: 'a становится b, а b — остатком a % b. Это шаг Евклида.' },
      { type: 'assemble', q: 'Шаг 3. Собери цикл Евклида',
        lines: ['while b > 0:', '    a, b = b, a % b', 'print(a)'],
        explain: 'Повторяем, пока b не станет 0. В a останется НОД.' },
    ],
    finalCode: 'a = int(input())\nb = int(input())\nwhile b > 0:\n    a, b = b, a % b\nprint(a)',
    example: { input: '12\n18', output: '6' },
  },
];
